#+TITLE: Desempleo y crecimiento del PIB
#+SETUPFILE: ../setup.org

#+cite_export: natbib ecta text
#+bibliography: unemp.bib

# Define macros for the variable names
#+LATEX_HEADER: \newcommand*{\unemp}{\Var{unemp}}
#+LATEX_HEADER: \newcommand*{\gY}{\Var{gY}}
#+LATEX_HEADER: \newcommand*{\covid}{\Var{covid}}


* Objetivo

Estimar la respuesta dinámica de la tasa de desempleo a las
variaciones en el crecimiento del PIB. Se estima un modelo de retardos
distribuidos con datos de España que cubren el periodo que va desde el
primer trimestre de 1980 hasta el tercero de 2023.

* Datos

La Secretaría de Estado de Presupuestos y Gastos proporciona varias
bases de datos desde su [[https://www.sepg.pap.hacienda.gob.es/sitios/sepg/es-ES/Presupuestos/DocumentacionEstadisticas/Documentacion/Paginas/Documentacion.aspx][página web]]. La base de datos [[https://www.sepg.pap.hacienda.gob.es/sitios/sepg/es-ES/Presupuestos/DocumentacionEstadisticas/Documentacion/paginas/basedatosmodelorems.aspx][BDREMS]]
proporciona series macroeconómicas para España que abarcan desde el
primer trimestre de 1980 al tercer trimestre de 2023 . Su periodicidad
es trimestral y, por lo general, se trata de series corregidas de
estacionalidad y de efecto calendario.  Las variables a precios
constantes tienen como referencia el año 2015.

El fichero =unemp.csv= contiene dos de las series de BDREMS:

- =PIBpm= es el PIB a precios de mercado en millones de euros
  constantes, y

- =unemp= es la tasa de paro.


** Transformación de las variables

Cree las variables:

- =ld_PIBpm=, la diferencia del logaritmo de =PIBpm=.

- =d_unemp=, la primera diferencia de la tasa de paro.

- =gY=, que se obtiene multiplicando =ld_PIBpm= por 100.


** Descripción de las variables

- En adelante, se usarán las series =d_unemp= y =gY=. ¿Qué
  interpretación económica tienen?

- Represente gráficamente y observe la evolución temporal de las
  variables =d_unemp= y =gY=.  ¿Se observan tendencias o algún otro
  tipo de no estacionariedad?

* Modelo estático

- Antes de proceder a la estimación del modelo estático, ajustaremos
  la muestra para que comience en el primer trimestre de 1982. De esta
  forma, aunque en etapas posteriores se introduzcan retardos, las
  estimaciones obtenidas seguirán siendo comparables con las del
  modelo estático, ya que se utilizará el mismo rango muestral en
  todas las especificaciones. Use el menú /Muestra | Establecer rango
  .../ para ajustar el periodo inicial.

- Estime por mínimos cuadrados ordinarios, MCO, los parámetros de:
  #+begin_export latex
  \begin{equation}\label{eq:1}
    \Delta \unemp_t = \alpha + \beta\, \gY_t + u_t,
  \end{equation}
  #+end_export
  donde $\unemp_t$ es la tasa de paro en el periodo $t$, $\gY_t$ es la tasa
  de crecimiento porcentual del PIB real y $u_t$ es el término de
  error.

- Evalúe la bondad del ajuste y la significación de la variable
  explicativa. ¿Cuál es la interpretación económica de los parámetros
  $\alpha$ y $\beta$?

- Obtenga un gráfico de series temporales de los residuos. Represente
  también el correlograma de los residuos. ¿Se comportan como un ruido
  blanco?


* Análisis de intervención

Con frecuencia, una serie temporal refleja el impacto de sucesos
exógenos que ocurren de forma puntual e imprevisible. Estos eventos,
conocidos como *intervenciones*, pueden provocar cambios
significativos en el nivel de la serie o dar lugar a valores extremos
(/outliers/) que no se corresponden con la evolución habitual de la
serie hasta ese momento. Para controlar estos efectos, se incorporan
en los modelos de regresión variables explicativas deterministas
diseñadas para captar el efecto específico de la intervención. Por
ejemplo, un *impulso* representa un cambio transitorio en el nivel de
la serie y se incorpora mediante una variable ficticia que toma valor
1 únicamente en el período afectado.



- Cree una variable de impulso, =covid=, para captar el inicio del
  confinamiento a causa de la COVID19. Para ello, seleccione la opción
  /Variable ficticia de rango de observación/ del menú /Añadir/ y
  especifique un rango cuyo principio y fin sea el segundo trimestre
  de 2020.

- Estime por MCO los parámetros de:
  #+begin_export latex
  \begin{equation}\label{eq:2}
    \Delta \unemp_t = \alpha + \beta\, \gY_t + \theta\, \covid_t + u_t,
  \end{equation}
  #+end_export
  Comente los resultados obtenidos y compárelos con los de la
  estimación de la ecuación \eqref{eq:1}.


* Modelo de retardos distribuidos

- Use el menú /Editar | Modificar el modelo.../ de la ventana de la
  estimación de la ecuación \eqref{eq:2} y añada 5 retardos de la
  variable =gY=. Así se obtienen las estimaciones del modelo de
  retardos distribuidos:
  #+begin_export latex
  \begin{equation}\label{eq:3}
    \Delta \unemp_t =
    \alpha +
    \beta_0\, \gY_t +
    \beta_1\, \gY_{t-1} +
    \dots +
    \beta_5\, \gY_{t-5} +
    \theta\, \covid_t + u_t,
  \end{equation}
  #+end_export
  ¿Qué significan los parámetros estimados? ¿Cómo responde la tasa de
  paro a cambios en el crecimiento del PIB?

- Para calcular el multiplicador de largo plazo, $\delta_L = \sum
  \beta_i$, introduzca en la consola de Gretl las instrucciones:
  #+latex: \vspace*{1ex}
  #+begin_src gretl :eval no
    mult = $coeff[2:7]
    mult_lp = sum(mult)
  #+end_src
  #+latex: \vspace*{1ex}
  ¿Qué significa el valor obtenido? /[Nota: Para que funcionen
  adecuadamente las instrucciones anteriores los parámetros de =gY= y
  sus retardos deben de ocupar las posiciones 2 a 7 en la tabla de la
  regresión.]/
- Los multiplicadores acumulados, $\delta_j = \sum_{i=0}^j\beta_i$, se
  obtienen introduciendo en la consola de Gretl las siguientes líneas:
  #+latex: \vspace*{1ex}
  #+begin_src gretl :eval no
        mult_ac = cum(mult)
        mult_ac
  #+end_src
  #+latex: \vspace*{1ex}
  ¿Que interpretación tienen estos multiplicadores?

- En [cite:@leon-ledesmaEndogeneityNaturalRate2002] se define la /tasa
  de crecimiento natural/ como aquella que mantiene constante el
  desempleo. El modelo de la ecuación \eqref{eq:3} implica que en
  equilibrio a largo plazo:
  #+begin_export latex
  \[
    \Delta \unemp_t =
    \alpha +
    \delta_L\, \gY.
  \]
  #+end_export
  La tasa de crecimiento natural sería la que hace que $\Delta
  \unemp_t = 0$, por lo que:
  #+begin_export latex
  \[
     \gY_n = -\alpha / \delta_L.
  \]
  #+end_export
  Esta tasa se puede obtener en la consola de Gretl con:
  #+latex: \vspace*{1ex}
  #+begin_src gretl :eval no
        gYn = -$coeff[1] / mult_lp
  #+end_src
  #+latex: \vspace*{1ex}
  De acuerdo con la estimación de la ecuación \eqref{eq:3}, ¿cuál
  sería la tasa trimestral de crecimiento necesaria para que no
  aumente el desempleo?


#+print_bibliography:


# Local Variables:
# ispell-local-dictionary: "spanish"
# End:

#  LocalWords:  Gretl
