#+TITLE: Consumo de tabaco y el peso de los recién nacidos
#+SETUPFILE: ../setup.org

#+LATEX_HEADER: \newcommand*{\weight}{\Var{weight}}
#+LATEX_HEADER: \newcommand*{\weightkg}{\Var{weightkg}}
#+LATEX_HEADER: \newcommand*{\faminc}{\Var{faminc}}
#+LATEX_HEADER: \newcommand*{\parity}{\Var{parity}}
#+LATEX_HEADER: \newcommand*{\first}{\Var{first}}
#+LATEX_HEADER: \newcommand*{\second}{\Var{second}}
#+LATEX_HEADER: \newcommand*{\male}  {\Var{male}}
#+LATEX_HEADER: \newcommand*{\white} {\Var{white}}
#+LATEX_HEADER: \newcommand*{\cigs}  {\Var{cigs}}
#+LATEX_HEADER: \newcommand*{\smoker}{\Var{smoker}}


* Objetivo

Mediante modelos de regresión lineal múltiple se tratará de establecer
si existe una relación de causalidad entre la salud de los recién
nacidos, aproximada por su peso al nacer, y el consumo de tabaco por
parte de sus madres durante el embarazo.

* Datos

Los datos fueron utilizados por J. Mullahy (1997):
"@@latex:\foreignlanguage{english}{Instrumental-Variable Estimation of
Count Data Models: Applications to Models of Cigarette Smoking
Behavior}@@", /@@latex:\foreignlanguage{english}{Review of Economics
and Statistics}@@/, 79, 596-593. El archivo ~bwght.csv~ contiene,
entre otras variables, los pesos de 1388 recién nacidos durante el año
1988 en Estados Unidos. Las variables disponibles son:

- \weight: peso al nacer, en onzas.
- \cigs: número de cigarrillos que la madre fumaba al día durante el embarazo.
- \male: variable ficticia, 1 si el recién nacido es hombre.
- \white: variable ficticia, 1 si el recién nacido es blanco.
- \parity: La [[https://es.wikipedia.org/wiki/Gravidez_y_paridad][paridad]] es el número de veces que una mujer ha dado a
  luz a un bebé que ha llegado a una edad gestacional viable. En la
  práctica, las madres primerizas, $\parity = 1$, suelen tener recién
  nacidos con un peso algo menor que el de mujeres que ya han tenido
  partos previos.
- \faminc: renta familiar, en miles de dólares.

** Transformación de variables

#+ATTR_LATEX: :options [a)]
a) Teniendo en cuenta que una onza son 29 gramos, cree una nueva
   variable, \weightkg, que exprese el peso de los recién nacidos en
   kg.

b) Cree una variable ficticia, \first, que tome el valor 1 para los
   recién nacidos que sean el primer hijo de su madre. Cree otra
   ficticia, \second, para los segundos hijos.

c) Cree una variable ficticia, \smoker, que tome el valor 1 para las
   madres que fumaron durante su embarazo.

d) Obtenga los logaritmos de las variables \faminc, \weight y
   \weightkg.


** Estadísticos descriptivos

A partir de los estadísticos descriptivos de las variables, responda a
las siguientes preguntas:

#+ATTR_LATEX: :options [a)]
a) ¿Cuál es el peso medio de los recién nacidos?

b) ¿Cuál era el número medio de cigarrillos que fumaron las madres de
   la muestra?

c) ¿Que proporción de madres fumaron durante el embarazo?

d) ¿Qué proporción representaban los varones entre los recién nacidos?


** Modelo de regresión

Considere el modelo de regresión lineal:
#+begin_export latex
\begin{equation*}
  \log(\weight) =
  \beta_{0}
  + \beta_{1} \smoker
  + u
\end{equation*}
#+end_export

#+ATTR_LATEX: :options [a)]
a) ¿Cuáles es el signo esperado de $\beta_{1}$?

b) Estime el modelo por Mínimos Cuadrados Ordinarios. Interprete las
   estimaciones. ¿Es posible dar una interpretación causal al modelo
   de regresión simple?

c) ¿Se obtienen resultados diferentes si se usa $\log(\weightkg)$ como
   variable dependiente?

d) Amplíe el modelo de regresión añadiendo las variables explicativas
   \male, \first, \second, \white y el logaritmo de
   \faminc. Interprete los resultados obtenidos. ¿Qué variables tienen
   efectos significativos sobre el peso de los recién nacidos? ¿Se
   observan cambios importantes en la estimación del parámetro de
   \smoker?


** Conclusión

¿Qué conclusiones pueden extraerse del análisis econométrico? ¿Existe
una relación causal entre el consumo del tabaco durante el embarazo y el
peso de los recién nacidos?


# Local Variables:
# ispell-local-dictionary: "spanish"
# End:
