#+TITLE: La función de consumo agregado
#+SETUPFILE: ../setup.org

# Define macros for the variable names
#+LATEX_HEADER: % \newcommand*{\weight}{\Var{weight}}


* Objetivo

Estimar una función de consumo agregado para los países fundadores del
área euro utilizando datos trimestrales de los años 1970--1998.

* Datos

El Banco Central Europeo, BCE, desarrolló un modelo econométrico con
los principales agregados macroeconómicos del área euro. El modelo
está descrito en [cite:@faganAreawideModelAWM2001] y la base de datos
que se elaboró está disponible en la página web del BCE ([[https://www.ecb.europa.eu/pub/pdf/annex/ecbwp42-annexes.zip?0388378b0ef95cfccc73aaa41ac5071d][enlace]]). Las
series tienen frecuencia trimestral y se construyeron agregando las
series desestacionalizadas de los países de la zona euro. Dos de esas
variables se incluyen en el fichero ~cons.csv~: ~PCR~ es el consumo
privado y ~PYR~ es la renta disponible de las familias. Ambas
variables se miden en términos reales y los datos cubren el periodo
que va desde el primer trimestre de 1970 hasta el segundo de 1998:


** Transformación de las variables

- Cree la variable ~c~ aplicando el logaritmo a la serie del consumo
  privado, ~PCR~.

- Cree la variable ~y~ calculando el logaritmo de la serie de la renta
  disponible de las familias, ~PYR~.


** Descripción de las variables

- Represente gráficamente y observe la evolución temporal de las
  series ~c~ e ~y~. ¿Son estacionarias?

- Calcule los *correlogramas* de las series ~c~ e ~y~. ¿Son
  compatibles con la propiedad de dependencia débil?


* Modelo en niveles

- Estime por mínimos cuadrados ordinarios, MCO, los parámetros de la
  función de consumo agregado:
  #+begin_export latex
  \begin{equation}\label{eq:1}
    c_t = \beta_0 + \beta_1 y_t + u_t,
  \end{equation}
  #+end_export
  donde $u_t$ es el término de error.

- Evalúe la bondad del ajuste y la significación de la variable
  explicativa.

- Obtenga un gráfico de series temporales de los residuos. Represente
  también el *correlograma* de los residuos. ¿Se comportan como un
  *ruido blanco*?

* Regresiones espurias

Las regresiones donde las variables presentan fuertes tendencias
pueden arrojar resultados aparentemente significativos, aun cuando no
exista ninguna relación causal entre las variables. Esta situación
puede ilustrarse reemplazando la variable $y_t$ en la
ecuación \eqref{eq:1} por la variable $rw_t$, un *paseo aleatorio con
deriva*.

- Use el menú ~Añadir~ e introduzca la siguiente definición:
  #+begin_center
  ~rw = 13 + cum(normal(0.006, 0.007))~
  #+end_center
  Esta expresión crea un paseo aleatorio con deriva con el generador
  de números aleatorios de Gretl.

- Considere ahora el modelo de regresión:
  #+begin_export latex
  \begin{equation}\label{eq:2}
    c_t = \alpha_0 + \alpha_1 \mathit{rw}_t + \text{error}_t.
  \end{equation}
  #+end_export
  Dado que $\mathit{rw}_t$ se ha generado aleatoriamente, no tiene
  relación con el consumo agregado y el parámetro $\alpha_1$ debe ser
  $0$.

  Estime los parámetros de la ecuación \eqref{eq:2} por MCO, evalúe la
  bondad del ajuste de la regresión y verifique la significación
  estadística de la variable $\mathit{rw}_t$. Compare el $R^2$ y la
  significación con los obtenidos en la estimación de la
  ecuación \eqref{eq:1}. ¿Qué sugiere esta comparación?


* Modelo en diferencias

Una forma habitual de evitar regresiones espurias cuando las variables
no son estacionarias es plantear modelos en diferencias.

- Calcule y represente gráficamente la primera diferencia de las
  variables, ~c~ e ~y~. ¿Las variables en diferencias son
  estacionarias? Examine los correlogramas y determine si hay
  problemas de dependencia fuerte.

- Estime por MCO los parámetros de la función de consumo agregado en
  diferencias:
  #+begin_export latex
  \begin{equation}\label{eq:3}
    \Delta c_t = \delta_0 + \delta_1 \Delta y_t + v_t,
  \end{equation}
  #+end_export
  donde $v_t$ es un término de error. Comente brevemente los
  resultados obtenidos.

- Genere un gráfico de series temporales de los residuos de la
  estimación de \eqref{eq:3} y represente su correlograma. ¿Se
  comportan como un *ruido blanco*?

- Obtenga la diferencia de ~rw~ y estime los parámetros de:
  #+begin_export latex
  \begin{equation}\label{eq:4}
    \Delta c_t = \gamma_0 + \gamma_1 \Delta \mathit{rw}_t + \text{error}_t,
  \end{equation}
  #+end_export
  Compare las estimaciones con las de la ecuación \eqref{eq:2}.

- A la vista de los resultados, ¿qué modelo considera más adecuado
  para analizar la relación entre consumo y renta?


#+print_bibliography:

# Local Variables:
# ispell-local-dictionary: "spanish"
# End:

#  LocalWords:  Gretl
