#+TITLE: Estimación de curvas de Engel
#+SETUPFILE: ../setup.org

# Define macros for the variable names
#+LATEX_HEADER: \newcommand*{\total}{\Var{total}}
#+LATEX_HEADER: \newcommand*{\ltotal}{\Var{ltotal}}
#+LATEX_HEADER: \newcommand*{\kids     }{\Var{kids     }}
#+LATEX_HEADER: \newcommand*{\age      }{\Var{age      }}
#+LATEX_HEADER: \newcommand*{\pctfood  }{\Var{pctfood  }}
#+LATEX_HEADER: \newcommand*{\pctclothes}{\Var{pctclothes}}
#+LATEX_HEADER: \newcommand*{\twokids  }{\Var{twokids  }}
#+LATEX_HEADER: \newcommand*{\food}{\Var{food}}
#+LATEX_HEADER: % \newcommand*{\}{\Var{}}


* Objetivo

Seleccionar entre distintas especificaciones de curvas de Engel,
mediante el uso de contrastes de hipótesis no anidadas.

* Datos

Los datos fueron utilizados en
[cite:@blundellSemiparametricEstimationConsumer1998] y provienen de la
Encuesta de Gastos Familiares británica (/Family Expenditure Survey/)
para los años 1980--1982. Los autores utilizan métodos avanzados para
estimar curvas de Engel de diferentes categorías de bienes
(alimentación, energía, etc.).

Se seleccionó una muestra relativamente homogénea de familias: parejas
con uno o dos hijos que viven en el sureste de Inglaterra y donde el
sustentador principal tiene un trabajo por cuenta ajena.  La selección
de la muestra se hace con respecto a las variables explicativas
(características demográficas), lo que no afecta a las propiedades de
insesgadez y consistencia de MCO. La utilización de una muestra
relativamente homogénea simplifica la especificación de las curvas de
Engel, pero limita la generalidad de los resultados.

En el fichero ~engel.csv~ se encuentran las siguientes variables:

- \total: gasto total en consumo (£ por semana).

- \food: gasto en alimentación (£ por semana).

- \kids: número de hijos (1 o 2).

- \age: edad del sustentador principal.


* Curvas de Engel

En los trabajos empíricos sobre consumo, es habitual emplear modelos
en los que la variable dependiente es el porcentaje del gasto total
que un consumidor o una familia destina a un determinado bien
(alimentos, por ejemplo). La variable dependiente se explica por una
función del gasto total y otras variables demográficas (edad, número
de hijos, etc.). En este laboratorio se estimarán modelos que son
casos particulares de:
#+begin_export latex
\[
  \pctfood = f(\total, \kids, \age),
\]
#+end_export
donde
#+begin_export latex
\[
  \pctfood = 100\,\frac{\food}{\total}.
\]
#+end_export
En el *Modelo A*, se incluyen como explicativas el gasto total y su
cuadrado:
#+begin_export latex
\[
   \pctfood =
   \beta_0 +
   \beta_1 \total +
   \beta_2 \total^2 +
   \beta_3 \twokids +
   \beta_4 \age +
   \beta_5 \age^2 +
   u
   \tag{Modelo A}
\]
#+end_export
La variable \twokids es una variable ficticia que toma el valor $1$ en
aquellas familias que tienen $2$ hijos.

En el *Modelo B* se utiliza el logaritmo del gasto total como explicativa:
#+begin_export latex
\[
   \pctfood =
   \alpha_0 +
   \alpha_1 \log(\total) +
   \alpha_2 \twokids +
   \alpha_3 \age +
   \alpha_4 \age^2 +
   v
   \tag{Modelo B}
\]
#+end_export


* Instrucciones

Asegúrese de usar errores típicos robustos a heteroscedasticidad en
todas las estimaciones y contrastes. Realice los contrastes a un nivel
de significación del \pct{5}.

#+ATTR_LATEX: :options [a)]
a) Cree las siguientes variables:
   - \pctfood: porcentaje que representan los gastos en alimentos
     sobre el gasto total de las familias.
   - \twokids: variable ficticia que toma el valor $1$ en las familias
     con 2 hijos.
   - Cree variables con el logaritmo de \total y con los cuadrados
     de \total y \age.
   ¿Cuál era, por término medio, el porcentaje del gasto total
   dedicado a alimentación? ¿Qué proporción de familias tenía 2 hijos?
   ¿Cuál era la edad media de los sustentadores principales?

   #+begin_answer

   #+end_answer

b) <<item_mcoa>>Estime por MCO los parámetros del Modelo A. Guarde los valores
   ajustados de la variable dependiente.

   #+begin_answer

   #+end_answer

c) <<item_mcob>>Estime el Modelo B por MCO y guarde las predicciones.

   #+begin_answer

   #+end_answer

d) Compare la bondad del ajuste de ambos modelos. ¿Cuál sería
   preferible de acuerdo con este criterio?

   #+begin_answer
     el $R^2$ ajustado.

     De acuerdo a este criterio el Modelo B sería preferible.
   #+end_answer

e) Use los contrastes de abarcamiento para evaluar la validez de cada
   uno de los modelos frente al otro. ¿Qué conclusión puede extraerse
   de estos contrastes?

   #+begin_answer
     Para llevar a cabo este tipo de contraste, primero fusionamos los
     dos modelos rivales:
     #+begin_export latex
     \[
       \pctfood} = \gamma_0
       + \gamma_1 \total
       + \gamma_2 \total^2
       + \gamma_3 \log(\total)
       + \gamma_4 \twokids
       + \gamma_5 \age
       + \gamma_6 \age^2
       + \text{error}
     \]
     #+end_export
     Ahora podemos expresar los dos modelo rivales como restricciones
     sobre los parámetros $\gamma_0, \gamma_1, \dots, \gamma_6$:

     - Modelo A: $H_0\!: \gamma_3 = 0$.

     - Modelo B: $H_0\!: \gamma_1 = \gamma_2 = 0$.

     Aplicamos esta estrategia a nuestros modelos (usando contrastes de
     significación robustos a heteroscedasticidad):

     - Estimamos un modelo que incluye las variables explicativas del
       Modelo A y del Modelo B:

     - Contrastamos la validez del Modelo A frente al B:

       El resultado del contraste llevaría al rechazo del Modelo A.

     - Contrastamos la validez del Modelo B frente al A:

       En este caso no podemos rechazar el Modelo B.

     Los contrastes de abarcamiento seleccionarían el Modelo B.

   #+end_answer

f) Utilice las predicciones guardadas en los apartados [[item_mcoa]] y
   [[item_mcob]] para comparar los dos modelos con los contrastes de
   Davidson-MacKinnon y comente los resultados.

   #+begin_answer
     Los contrastes propuestos por Davidson y MacKinnon consisten en
     ampliar cada uno de los modelos con las predicciones del modelo
     rival. Si un modelo está correctamente especificado, las predicciones
     obtenidas con un modelo rival no deberían tener poder explicativo.

     - Modelo A:

       El contraste $t$ robusto a heteroscedasticidad muestra que las
       predicciones del modelo B tienen capacidad explicativa. Por tanto,
       rechazamos el modelo A.

     - Modelo B:

       En este caso las predicciones de Modelo A no son significativas, por
       lo que no rechazaríamos la hipótesis de correcta especificación del
       Modelo B.

     Los contrastes de Davidson-MacKinnon también seleccionarían el
     Modelo B.

   #+end_answer


#+print_bibliography:

# Local Variables:
# ispell-local-dictionary: "spanish"
# End:

#  LocalWords:  Engel Family Expenditure Survey Davidson MacKinnon
