#+TITLE: Estimación de curvas de Engel
#+SETUPFILE: ../setup.org

# Define macros for the variable names
#+LATEX_HEADER: \newcommand*{\total}{\Var{total}}
#+LATEX_HEADER: \newcommand*{\ltotal}{\Var{ltotal}}
#+LATEX_HEADER: \newcommand*{\kids     }{\Var{kids     }}
#+LATEX_HEADER: \newcommand*{\age      }{\Var{age      }}
#+LATEX_HEADER: \newcommand*{\pctfood  }{\Var{pctfood  }}
#+LATEX_HEADER: \newcommand*{\pctclothes}{\Var{pctclothes}}
#+LATEX_HEADER: \newcommand*{\twokids  }{\Var{twokids  }}
#+LATEX_HEADER: \newcommand*{\food}{\Var{food}}
#+LATEX_HEADER: % \newcommand*{\}{\Var{}}


* Objetivo

Seleccionar entre distintas especificaciones de curvas de Engel,
mediante el uso de contrastes de hipótesis no anidadas.

* Datos

Los datos fueron utilizados en
[cite:@blundellSemiparametricEstimationConsumer1998] y provienen de la
Encuesta de Gastos Familiares británica (/Family Expenditure Survey/)
para los años 1980--1982. Los autores utilizan métodos avanzados para
estimar curvas de Engel de diferentes categorías de bienes
(alimentación, energía, etc.).

Se seleccionó una muestra relativamente homogénea de familias: parejas
con uno o dos hijos que viven en el sureste de Inglaterra y donde el
sustentador principal tiene un trabajo por cuenta ajena.  La selección
de la muestra se hace con respecto a las variables explicativas
(características demográficas), lo que no afecta a las propiedades de
insesgadez y consistencia de MCO. La utilización de una muestra
relativamente homogénea simplifica la especificación de las curvas de
Engel, pero limita la generalidad de los resultados.

En el fichero ~engel.csv~ se encuentran las siguientes variables:

- \total: gasto total en consumo (£ por semana).

- \food: gasto en alimentación (£ por semana).

- \kids: número de hijos (1 o 2).

- \age: edad del sustentador principal.


* Curvas de Engel

En los trabajos empíricos sobre consumo, es habitual emplear modelos
en los que la variable dependiente es el porcentaje del gasto total
que un consumidor o una familia destina a un determinado bien
(alimentos, por ejemplo). La variable dependiente se explica por una
función del gasto total y otras variables demográficas (edad, número
de hijos, etc.). En este laboratorio se estimarán modelos que son
casos particulares de:
#+begin_export latex
\[
  \pctfood = f(\total, \kids, \age),
\]
#+end_export
donde
#+begin_export latex
\[
  \pctfood = 100\,\frac{\food}{\total}.
\]
#+end_export
En el *Modelo A*, se incluyen como explicativas el gasto total y su
cuadrado:
#+begin_export latex
\[
   \pctfood =
   \beta_0 +
   \beta_1 \total +
   \beta_2 \total^2 +
   \beta_3 \twokids +
   \beta_4 \age +
   \beta_5 \age^2 +
   u
   \tag{Modelo A}
\]
#+end_export
La variable \twokids es una variable ficticia que toma el valor $1$ en
aquellas familias que tienen $2$ hijos.

En el *Modelo B* se utiliza el logaritmo del gasto total como explicativa:
#+begin_export latex
\[
   \pctfood =
   \alpha_0 +
   \alpha_1 \log(\total) +
   \alpha_2 \twokids +
   \alpha_3 \age +
   \alpha_4 \age^2 +
   v
   \tag{Modelo B}
\]
#+end_export


* Instrucciones

Asegúrese de usar errores típicos robustos a heteroscedasticidad en
todas las estimaciones y contrastes. Realice los contrastes a un nivel
de significación del \pct{5}.

#+ATTR_LATEX: :options [a)]
a) Cree las siguientes variables:
   - \pctfood: porcentaje que representan los gastos en alimentos
     sobre el gasto total de las familias.
   - \twokids: variable ficticia que toma el valor $1$ en las familias
     con 2 hijos.
   - Cree variables con el logaritmo de \total y con los cuadrados
     de \total y \age.
   ¿Cuál era, por término medio, el porcentaje del gasto total
   dedicado a alimentación? ¿Qué proporción de familias tenía 2 hijos?
   ¿Cuál era la edad media de los sustentadores principales?

   #+begin_answer
   Una vez creadas las nuevas variables, se calculan los estadísticos
   descriptivos necesarios para responder a las preguntas:
   #+latex: \gretl[lastline=5]{engel-a.txt}
   Los valores medios de las  variables muestran que:
   - Las familias de la muestra dedicaban a alimentación el \pct{35.6}
     de su gasto total, por término medio.
   - El \pct{60.9} de las familias tenía $2$ hijos.
   - La edad media de los sustentadores principales era de $35.8$
     años.
   #+end_answer
   #+latex: \ClearPage{}

b) <<item_mcoa>>Estime por MCO los parámetros del Modelo A. Guarde los valores
   ajustados de la variable dependiente.

   #+begin_answer
   Estimación por MCO del Modelo A:
   #+latex: \gretl[lastline=18]{engel-b.txt}

   Las predicciones se guardan en la variable ~yhat_A~.
   #+end_answer

c) <<item_mcob>>Estime el Modelo B por MCO y guarde las predicciones.

   #+begin_answer
   Estimación por MCO del Modelo B:
   #+latex: \gretl[lastline=17]{engel-c.txt}

   Las predicciones se guardan en la variable ~yhat_B~.
   #+end_answer

d) Compare la bondad del ajuste de ambos modelos. ¿Cuál sería
   preferible de acuerdo con este criterio?

   #+begin_answer
     Puesto que los dos modelos que se están comparando tienen un
     número diferente de variables explicativas se utilizará el $R^2$
     ajustado para comparar la bondad del ajuste:
     #+begin_export latex
     \[
     \bar{R}^2_A = 0.282, \quad \bar{R}^2_B = 0.286.
     \]
     #+end_export

     De acuerdo con este criterio, el Modelo B sería preferible ya que
     su $R^2$ ajustado es ligeramente superior al del Modelo A.
   #+end_answer
   #+latex: \ClearPage{}

e) Use los contrastes de abarcamiento para evaluar la validez de cada
   uno de los modelos frente al otro. ¿Qué conclusión puede extraerse
   de estos contrastes?

   #+begin_answer
     Para llevar a cabo este tipo de contraste, se estima una
     regresión con todas las variables explicativas de los dos modelos
     rivales:
     #+begin_export latex
     \[
       \pctfood = \gamma_0
       + \gamma_1 \total
       + \gamma_2 \total^2
       + \gamma_3 \log(\total)
       + \gamma_4 \twokids
       + \gamma_5 \age
       + \gamma_6 \age^2
       + \text{error}
     \]
     #+end_export
     Cada uno de los modelos se puede obtener mediante restricciones
     sobre los parámetros $\gamma_0, \gamma_1, \dots, \gamma_6$:

     - Modelo A: $H_0\!: \gamma_3 = 0$.

     - Modelo B: $H_0\!: \gamma_1 = \gamma_2 = 0$.

     Se estima, en primer lugar, la regresión de abarcamiento por MCO:
     #+latex: \gretl[lastline=16]{engel-e1.txt}
     #+latex: \vspace*{1ex}

     Contraste del Modelo A frente al Modelo B:
     #+latex: \gretl[lastline=3]{engel-e2.txt}
     Se rechazaría el Modelo A al \pct{5} de significación.
     #+latex: \vspace*{1ex}

     Contraste del Modelo B frente al Modelo A:
     #+latex: \gretl[lastline=4]{engel-e3.txt}
     En este caso, no se puede rechazar la validez del Modelo B para
     $\alpha = \pct{5}$.
     #+latex: \vspace*{1ex}

     Los contrastes de abarcamiento rechazarían el Modelo A en favor
     del Modelo B.
   #+end_answer
   #+latex: \ClearPage{}

f) Utilice las predicciones guardadas en los apartados [[item_mcoa]] y
   [[item_mcob]] para comparar los dos modelos con los contrastes de
   Davidson-MacKinnon y comente los resultados.

   #+begin_answer
     Estimación del Modelo A cuando se incluye como explicativa
     adicional las predicciones del otro modelo:
     #+latex: \gretl[lastline=16]{engel-f1.txt}
     #+latex: \vspace*{1ex}

     Contraste de significación de $\hat{y}_B$:
     #+latex: \gretl[lastline=3]{engel-f2.txt}
     El contraste muestra que las predicciones del Modelo B tienen
     capacidad explicativa, por tanto, se rechaza el Modelo A.
     #+latex: \vspace*{1ex}

     Estimación del Modelo B cuando se añaden las predicciones del
     Modelo A:
     #+latex: \gretl[lastline=15]{engel-f3.txt}
     #+latex: \vspace*{1ex}

     Contraste de significación de $\hat{y}_A$:
     #+latex: \gretl[lastline=3]{engel-f4.txt}
     En este caso, las predicciones de Modelo A no son significativas,
     por lo que no se rechazaría la hipótesis de correcta
     especificación del Modelo B.
     #+latex: \vspace*{1ex}

     Los contrastes de Davidson-MacKinnon también seleccionarían el
     Modelo B.
   #+end_answer

#+print_bibliography:

# Local Variables:
# ispell-local-dictionary: "spanish"
# End:

#  LocalWords:  Engel Family Expenditure Survey Davidson MacKinnon
