#+TITLE: Exportaciones y crecimiento económico
#+SETUPFILE: ../setup.org

# Define macros for the variable names
#+LATEX_HEADER: % \newcommand*{\weight}{\Var{weight}}


* Objetivo

Examinar la relación entre el crecimiento económico y la evolución de
las exportaciones en el caso de España durante el periodo 1983--2023.

* Datos

La Secretaría de Estado de Presupuestos y Gastos proporciona varias
bases de datos desde su [[https://www.sepg.pap.hacienda.gob.es/sitios/sepg/es-ES/Presupuestos/DocumentacionEstadisticas/Documentacion/Paginas/Documentacion.aspx][página web]]. La base de datos [[https://www.sepg.pap.hacienda.gob.es/sitios/sepg/es-ES/Presupuestos/DocumentacionEstadisticas/Documentacion/paginas/basedatosmodelorems.aspx][BDREMS]]
proporciona series macroeconómicas para España que abarcan desde el
primer trimestre de 1980 al tercer trimestre de 2023. La periodicidad
de las series es trimestral y, por lo general, se han corregido de
estacionalidad y efecto calendario.  Las variables a precios
constantes tienen como referencia el año 2015.

El fichero =exports.csv= contiene dos de las series de BDREMS:

- =PIBpm= es el PIB a precios de mercado en millones de euros
  constantes, y

- =exports= son las exportaciones de bienes y servicios, en millones
  de euros constantes.


* Instrucciones


#+begin_tcolorbox
- Realice los contrastes con un nivel de significación del 5%; en su
  caso, estime intervalos de confianza al 95%.

- Todas las estimaciones y contrastes deben realizarse para el periodo
  muestral 1983:1--2023:3, independientemente de los retardos que se
  usen.

- Asegúrese de establecer la muestra completa antes de crear o
  transformar variables.

- Utilice un máximo de 8 retardos en las regresiones o contrastes.
#+end_tcolorbox


** Transformación de las variables

- Cree las variables =lx= y =ly= correspondientes al logaritmo de las
  exportaciones y del PIB, respectivamente.

- A partir de las diferencias de =lx= y =ly=, cree las variables =gx=
  y =gy= que son, respectivamente, las tasas de crecimiento trimestral
  de las exportaciones y del PIB en tantos por 100.

- Cree =covid=, una variable de impulso para el inicio del
  confinamiento de la pandemia de la COVID-19 que sólo toma el valor 1
  en el segundo trimestre de 2020. *Además, añada la primera
  diferencia de =covid= a la base de datos*.

** Contrastes de raíces unitarias

- Contraste la presencia de raíces unitarias en las variables =lx=,
  =gx=, =ly= y =gy=.

- ¿Qué problemas podrían aparecer si se estima un modelo de regresión
  de =ly= con =lx= como variable explicativa? Si, en lugar de usar las
  variables en niveles, se emplean las tasas de crecimiento =gy= y
  =gx=, ¿seguirían presentándose los mismos problemas?

** Selección del número de retardos

- Determine el número óptimo de retardos en un modelo de retardos
  distribuidos con variable dependiente =gy= y variable explicativa
  =gx=. *Incluya en todas las regresiones que realice la primera
  diferencia de =covid=*.

- Presente los resultados de la estimación del modelo seleccionado en
  el punto anterior. Emplee errores típicos robustos a
  heteroscedasticidad y autocorrelación.

- Incluya en el modelo un retardo de la variable dependiente. ¿Es
  necesario incluir este retardo?

** Multiplicadores dinámicos

- Obtenga los multiplicadores acumulados y el multiplicador de largo
  plazo. Si es posible, obtenga sus errores típicos.

- Interprete los multiplicadores dinámicos, los acumulados y, en
  especial, los multiplicadores de corto y largo plazo.


** Cambio estructural

- Finalmente, examine la existencia de un cambio estructural que
  comience con la Gran Recesión. Con este propósito, cree una variable
  de intervención de tipo escalón que tome el valor 1 en el primer
  trimestre de 2008 y en todos los posteriores. Cree también la
  interacción de esta variable ficticia con la variable =gx=.

- Añada la variable de escalón y su interacción con =gx= y sus
  retardos al modelo de retardos distribuidos que obtuvo en la sección
  [[*Selección del número de retardos]]. Estime este modelo ampliado por
  MCO usando errores típicos robustos a heteroscedasticidad y
  autocorrelación.

- Contraste la significación de los términos añadidos en el punto
  anterior. Interprete los resultados obtenidos.


# Local Variables:
# ispell-local-dictionary: "spanish"
# End:

#  LocalWords:  PIB COVID
