#+TITLE: El precio de venta de las casas
#+SETUPFILE: ../setup.org

# Define macros for the variable names
#+LATEX_HEADER: \newcommand*{\hprice}{\Var{price}}
#+LATEX_HEADER: \newcommand*{\bedrooms}{\Var{bedrooms}}
#+LATEX_HEADER: \newcommand*{\colonial}{\Var{colonial}}
#+LATEX_HEADER: \newcommand*{\lotsize}{\Var{lotsize}}
#+LATEX_HEADER: \newcommand*{\size}{\Var{size}}


* Objetivo

Se emplean modelos de regresión hedónica para analizar el precio de
venta de las casas. Este tipo de modelos explica el precio de un bien
como función de sus características observables.


* Datos

Los datos proceden de la sección inmobiliaria del periódico /The
Boston Globe/ durante el año 1990. Este conjunto de datos se usa en
múltiples capítulos del manual de econometría de Wooldridge. Las
variables disponibles en el fichero ~hprice1.csv~ son:

- \hprice: precios de venta de las casas, miles de dólares.

- \bedrooms: número de habitaciones.

- \colonial: variable ficticia que toma el valor 1 para las casas con
  estilo colonial.

- \lotsize: tamaño del jardín, en metros cuadrados.

- \size: tamaño de la vivienda, en metros cuadrados.

* Instrucciones

Responda a las preguntas que aparecen a continuación. Use un nivel de
significación del $5\%$ para los contrastes.

** Estimación MCO

#+ATTR_LATEX: :options [a)]
a) Estime un modelo de regresión por mínimos cuadrados ordinarios
   (MCO) donde la variable dependiente es \hprice, y las explicativas
   son \bedrooms, \colonial, \lotsize y \size:
   #+begin_export latex
   \begin{equation*}
     \hprice_{i} =
     \beta_{0}
     + \beta_{1} \bedrooms_{i}
     + \beta_{2} \colonial_{i}
     + \beta_{3} \lotsize_{i}
     + \beta_{4} \size_{i}
     + u _{i}.
   \end{equation*}
   #+end_export
   ¿Qué variables tienen un efecto significativo sobre el precio de
   venta?  Interprete las estimaciones de los parámetros.

   #+latex: \begin{answer}
   La tabla siguiente muestra los resultados de la estimación del
   modelo de regresión por mínimos cuadrados ordinarios.

   #+latex: \gretl{hprice1-a.txt}

   A un nivel de significación $\alpha = 5\%$, solo dos variables
   presentan un efecto estadísticamente significativo sobre el precio
   de las viviendas: el tamaño de la parcela, \lotsize, y la superficie de
   la vivienda, \size (los valores-$p$ son \num{0.002} y menos que
   $0.001$, respectivamente). Por el contrario, las variables
   \bedrooms y \colonial no tienen efectos estadísticamente
   significativos.

   La estimación del parámetro de \lotsize indica que por cada metro
   cuadrado adicional del tamaño de la parcela, el precio de venta
   aumentaría en poco más de $22$ dólares, manteniendo constantes el
   resto de variables. Por otro lado, el coeficiente de \size muestra
   que, /ceteris paribus/, el precio de venta aumenta en algo más de
   \num{1300} dólares por cada metro cuadrado adicional de
   superficie. El parámetro de \bedrooms mide en cuánto aumentaría el
   precio si la vivienda tuviera una habitación adicional (unos
   \num{11000} dólares). Por último, la estimación del parámetro de
   \colonial indica que, a igualdad del resto de características, las
   casas de estilo colonial se venden por $13.7$ miles de dolares más
   que el resto de las casas.
   #+latex: \end{answer}

b) Obtenga los resultados de la estimación del modelo de regresión del
   apartado anterior usando errores típicos robustos a
   heteroscedasticidad. ¿Cambian las estimaciones de los parámetros?
   ¿Varía la bondad del ajuste? ¿Se altera la significación de la
   regresión? ¿Se modifica la significación individual de las
   variables?

   #+latex: \begin{answer}
   A continuación se muestran los resultados de la estimación del
   modelo de regresión hedónica por MCO usando errores típicos
   robustos a heteroscedasticidad.

   #+latex: \gretl{hprice1-b.txt}

   El uso de errores típicos robustos no afecta ni a las estimaciones
   de los parámetros ni a la bondad del ajuste medida por el $R^2$, el
   $R^2$ ajustado o el error típico de la regresión,
   $\hat{\sigma}$. Por otro lado, sí que se ven afectados los
   contrastes de significación individual de los parámetros (los
   estadísticos $t$) y la significación conjunta de la regresión (el
   estadístico $F$).

   El estadístico $F$ de significación conjunta de la regresión es
   considerablemente menor cuando se usan errores típicos
   robustos. Aún así, se rechaza al $5\%$ la hipótesis nula de
   ausencia de capacidad explicativa.

   Con respecto a la significación individual de las variables
   explicativas, la variación más importante se produce con
   \lotsize. Cuando se usan errores típicos robustos a
   heteroscedasticidad, el efecto de esta variable no es
   estadísticamente significativo para $\alpha = 5\%$ (valor $p =
   0.11$). La única pendiente que es significativamente distinta de
   $0$ es \size.
   #+latex: \end{answer}

** Contrastes de heteroscedasticidad


#+ATTR_LATEX: :options [a), start = 3]
c) Contraste el supuesto de heteroscedasticidad usando el contraste de
   Breusch-Pagan (Koenker).

   #+latex: \begin{answer}
   El contraste de Breusch-Pagan-Koenker, cuyos resultados aparecen a
   continuación, conduce a un fuerte rechazo de la hipótesis nula de
   homoscedasticidad (valor $p \approx 0.003 < \alpha = 0.05$).

   #+latex: \gretl{hprice1-c.txt}
   #+latex: \end{answer}

d) Utilice también el contraste de White y la alternativa propuesta
   por Wooldridge.

   #+latex: \begin{answer}
   Con el contraste de White también se rechaza fuertemente la
   hipótesis nula a un nivel de significación del $5\%$:
   #+latex: \gretl{hprice1-d1.txt}

   Wooldridge propone una alternativa que usa solo 2 explicativas en
   la regresión auxiliar, muchas menos que las 13 que se necesitan en
   el contraste originalmente propuesto por White. La variable
   dependiente de la regresión auxiliar es $\Var{uhat\_sq}$, los
   residuos al cuadrado. Los regresores son $\Var{yhat}$ y
   $\Var{yhat\_sq}$, las predicciones y las predicciones al cuadrado,
   respectivamente.

   #+latex: \gretl{hprice1-d2.txt}

   El contraste $F$ de significación de la regresión auxiliar rechaza
   la hipótesis nula (valor $p < 0.001 < \alpha = 5\%$), por lo que
   también con este contraste se encuentra fuerte evidencia de
   heteroscedasticidad.
   #+latex: \end{answer}

e) ¿Hay indicios de heteroscedasticidad? ¿Son válidos los resultados
   que se obtuvieron con MCO? ¿Es necesario el uso de errores típicos
   robustos?

   #+latex: \begin{answer}
   Los tres contrastes indican que hay fuerte evidencia de
   heteroscedasticidad y, por tanto, los errores típicos
   convencionales de MCO no son válidos. En consecuencia, los
   contrastes mostrados en la tabla del apartado a) no serían
   válidos. En cambio, los resultados del apartado b) sí pueden usarse
   aún en presencia de heteroscedasticidad.
   #+latex: \end{answer}


** Mínimos cuadrados ponderados

#+ATTR_LATEX: :options [a), start = 6]
f) Obtenga las estimaciones de mínimos cuadrados ponderados (MCP) bajo
   el supuesto de que la varianza condicional del término de error es
   proporcional a \lotsize:
   #+begin_export latex
   \begin{equation*}
     E(u^{2}_{i} | \bm{x}_{i}) = \sigma^{2}\lotsize_{i}.
   \end{equation*}
   #+end_export
   ¿Qué variables tienen efectos significativos? ¿Son similares las
   estimaciones a las obtenidas con MCO? Obtenga los resultados de la
   estimación MCP con errores típicos robustos a
   heteroscedasticidad. ¿Hay algún cambio en la significación de las
   variables? ¿Puede dar una explicación a esos cambios?

   #+latex: \begin{answer}
   El estimador MCP pondera las observaciones según la inversa de la
   varianza del error. Como esta se supone que es proporcional a
   \lotsize, se emplean ponderaciones inversamente proporcionales a esta
   variable, $w = 1 / \lotsize$.

   #+latex: \gretl[lastline=13]{hprice1-f1.txt}

   Los resultados de la estimación MCP muestran que las variables \lotsize
   y \size tienen efectos significativos sobre el precio de venta de las
   casas. Los efectos de \bedrooms y \colonial se estiman de forma
   imprecisa y no hay evidencia de que sean distintos de $0$.

   Se observan diferencias entre las estimaciones de los parámetros
   obtenidas con MCP y las obtenidas con MCO. En particular, el efecto
   estimado de \lotsize es más del doble que el obtenido en el
   apartado a).  En el caso de \size, el efecto estimado se reduce en
   un \pct{20}.

   La siguiente tabla muestra las estimaciones MCP empleando errores
   típicos robustos a heteroscedasticidad.

   #+latex: \gretl[lastline=14]{hprice1-f2.txt}

   En el caso de MCP, el uso de errores típicos robustos no se traduce en
   cambios drásticos. Aunque, en general, los errores típicos son algo
   mayores, no se altera la significación de las variables. Esto
   sugiere que la mayor parte de la heteroscedasticidad se habría
   corregido con las ponderaciones inversamente proporcionales al tamaño
   de la parcela.
   #+latex: \end{answer}

g) Aplique el método de mínimos cuadrados ponderados factibles de
   acuerdo con el supuesto:
   #+begin_export latex
   \begin{equation*}
     E(u^{2}_{i} | \bm{x}_{i}) = \sigma^{2}\exp\big(
     \delta_{0}
     + \delta_{1} \bedrooms_{i}
     + \delta_{2} \colonial_{i}
     + \delta_{3} \lotsize_{i}
     + \delta_{4} \size_{i}
     \big).
   \end{equation*}
   #+end_export
   Siga el procedimiento descrito en la sección /La
   heteroscedasticidad debe ser estimada: MCG factibles/ en las
   páginas 282 y siguientes del manual de Wooldridge. Obtenga los
   resultados con errores típicos robustos a heteroscedasticidad. ¿Qué
   conclusiones se pueden extraer?

   #+latex: \begin{answer}
   Se crea una nueva variable, \Var{l\_uhat\_sq}, definida como el
   logaritmo de los residuos de MCO al cuadrado: $\Var{l\_uhat\_sq} =
   \log(\hat{u}^2)$. Esta se utiliza como variable dependiente en una
   regresión frente a las variables \bedrooms, \colonial, \lotsize y
   \size.

   #+latex: \gretl{hprice1-g1.txt}

   Posteriormente, se construye la variable $h$ aplicando la función
   exponencial a los valores ajustados de esta regresión. Finalmente,
   se estima el modelo del precio de las casas por MCPF, usando como
   ponderación $w = 1 / h$,

   #+latex: \gretl[lastline=14]{hprice1-g2.txt}

   Los resultados son bastante similares a los obtenidos en el
   apartado anterior. No se observan diferencias importantes ni en la
   estimación de los parámetros ni en la significación de las
   variables.  La mayor diferencia se encuentra en el parámetro de
   \bedrooms, cuya variación se puede explicar por la escasa precisión
   con la que se estima el efecto de esta variable.

   En resumen, los resultados de las distintas estimaciones indican que
   el tamaño de la casa y de la parcela son importantes a la hora de
   determinar el precio al que se venden las viviendas, y que es esencial
   corregir la heteroscedasticidad para obtener conclusiones fiables
   sobre su significación estadística.
   #+latex: \end{answer}


# Local Variables:
# ispell-local-dictionary: "spanish"
# End:

#  LocalWords:  Breusch Koenker Wooldridge MCP MCG MCPF White
