#+TITLE: El precio de venta de las casas
#+SETUPFILE: ../setup.org

# Define macros for the variable names
#+LATEX_HEADER: \newcommand*{\hprice}{\Var{price}}
#+LATEX_HEADER: \newcommand*{\bedrooms}{\Var{bedrooms}}
#+LATEX_HEADER: \newcommand*{\colonial}{\Var{colonial}}
#+LATEX_HEADER: \newcommand*{\lotsize}{\Var{lotsize}}
#+LATEX_HEADER: \newcommand*{\size}{\Var{size}}



* Objetivo

Se emplean modelos de regresión hedónica para analizar el precio de
venta de las casas. Este tipo de modelos explica el precio de un bien
como función de sus características observables.


* Datos

Los datos proceden de la sección inmobiliaria del periódico /The
Boston Globe/ durante el año 1990. Este conjunto de datos se usa en
múltiples capítulos del manual de econometría de Wooldridge. Las
variables disponibles en el fichero ~hprice1.csv~ son:

- \hprice: precios de venta de las casas, miles de dólares.

- \bedrooms: número de habitaciones.

- \colonial: variable ficticia que toma el valor 1 para las casas con
  estilo colonial.

- \lotsize: tamaño del jardín, en metros cuadrados.

- \size: tamaño de la vivienda, en metros cuadrados.

* Instrucciones

Responda a las preguntas que aparecen a continuación. Use un nivel de
significación del $5\%$ para los contrastes.

** Estimación MCO

#+ATTR_LATEX: :options [a)]
a) Estime un modelo de regresión por mínimos cuadrados ordinarios
   (MCO) donde la variable dependiente es \hprice, y las explicativas
   son \bedrooms, \colonial, \lotsize y \size:
   #+begin_export latex
   \begin{equation*}
     \hprice_{i} =
     \beta_{0}
     + \beta_{1} \bedrooms_{i}
     + \beta_{2} \colonial_{i}
     + \beta_{3} \lotsize_{i}
     + \beta_{4} \size_{i}
     + u _{i}.
   \end{equation*}
   #+end_export
   ¿Qué variables tienen un efecto significativo sobre el precio de
   venta?  Interprete las estimaciones de los parámetros.

b) Obtenga los resultados de la estimación del modelo de regresión del
   apartado anterior usando errores típicos robustos a
   heteroscedasticidad. ¿Cambian las estimaciones de los parámetros?
   ¿Varía la bondad del ajuste? ¿Se altera la significación de la
   regresión? ¿Se modifica la significación individual de las
   variables?

** Contrastes de heteroscedasticidad


#+ATTR_LATEX: :options [a), start = 3]
c) Contraste el supuesto de heteroscedasticidad usando el contraste de
   Breusch-Pagan (Koenker).
d) Utilice también el contraste de White y la alternativa propuesta
   por Wooldridge.
e) ¿Hay indicios de heteroscedasticidad? ¿Son válidos los resultados
   que se obtuvieron con MCO? ¿Es necesario el uso de errores típicos
   robustos?

** Mínimos cuadrados ponderados

#+ATTR_LATEX: :options [a), start = 6]
d) Obtenga las estimaciones de mínimos cuadrados ponderados (MCP) bajo
   el supuesto de que la varianza condicional del término de error es
   proporcional a \lotsize:
   #+begin_export latex
   \begin{equation*}
     E(u^{2}_{i} | \bm{x}_{i}) = \sigma^{2}\lotsize_{i}.
   \end{equation*}
   #+end_export
   ¿Qué variables tienen efectos significativos? ¿Son similares las
   estimaciones a las obtenidas con MCO? Obtenga los resultados de la
   estimación MCP con errores típicos robustos a
   heteroscedasticidad. ¿Hay algún cambio en la significación de las
   variables? ¿Puede dar una explicación a esos cambios?

e) Aplique el método de mínimos cuadrados ponderados factibles de
   acuerdo con el supuesto:
   #+begin_export latex
   \begin{equation*}
     E(u^{2}_{i} | \bm{x}_{i}) = \sigma^{2}\exp\big(
     \delta_{0}
     + \delta_{1} \bedrooms_{i}
     + \delta_{2} \colonial_{i}
     + \delta_{3} \lotsize_{i}
     + \delta_{4} \size_{i}
     \big).
   \end{equation*}
   #+end_export
   Siga el procedimiento descrito en la sección /La
   heteroscedasticidad debe ser estimada: MCG factibles/ en las
   páginas 282 y siguientes del manual de Wooldridge. Obtenga los
   resultados con errores típicos robustos a heteroscedasticidad. ¿Qué
   conclusiones se pueden extraer?


# Local Variables:
# ispell-local-dictionary: "spanish"
# End:

#  LocalWords:  Breusch Koenker Wooldridge
