#+TITLE: El precio de venta de las casas --- Soluciones
#+SETUPFILE: ../setup.org

# Define macros for the variable names
#+LATEX_HEADER: \newcommand*{\hprice}{\Var{price}}
#+LATEX_HEADER: \newcommand*{\bedrooms}{\Var{bedrooms}}
#+LATEX_HEADER: \newcommand*{\colonial}{\Var{colonial}}
#+LATEX_HEADER: \newcommand*{\lotsize}{\Var{lotsize}}
#+LATEX_HEADER: \newcommand*{\size}{\Var{size}}


#+LATEX_HEADER: \usepackage{fbox}
#+LATEX_HEADER: \usepackage{fancyvrb}
#+LATEX_HEADER: \fvset{fontsize=\footnotesize,frame=lines,framerule=0.4pt}
#+LATEX_HEADER: \newcommand{\gretl}[2][]{\begin{center}\fbox*[tb]{\BVerbatimInput[#1]{#2}}\end{center}}


#+begin_tcolorbox
#+ATTR_LATEX: :options [a), series = questions]
a) <<item:a>>Estime un modelo de regresión por mínimos cuadrados
   ordinarios (MCO) donde la variable dependiente es \hprice, y las
   explicativas son \bedrooms, \colonial, \lotsize y \size:
   #+begin_export latex
   \begin{equation*}
     \hprice_{i} =
     \beta_{0}
     + \beta_{1} \bedrooms_{i}
     + \beta_{2} \colonial_{i}
     + \beta_{3} \lotsize_{i}
     + \beta_{4} \size_{i}
     + u _{i}.
   \end{equation*}
   #+end_export
   ¿Qué variables tienen un efecto significativo sobre el precio de
   venta?  Interprete las estimaciones de los parámetros de \lotsize
   y \size.
#+end_tcolorbox

#+latex: \gretl{hprice1-a.txt}

#+begin_tcolorbox
#+ATTR_LATEX: :options [a), resume = questions]
b) <<item:b>>Obtenga los resultados de la estimación del modelo de
   regresión del apartado anterior usando errores típicos robustos a
   heteroscedasticidad. ¿Cambian las estimaciones de los parámetros?
   ¿Es diferente la bondad del ajuste? ¿Cambia la significación de los
   parámetros?
#+end_tcolorbox

#+latex: \gretl{hprice1-b.txt}


#+begin_tcolorbox
#+ATTR_LATEX: :options [a), resume = questions]
c) De acuerdo con el contraste de Breusch-Pagan (Koenker), ¿hay
   indicios de heteroscedasticidad? ¿Y si se usa el contraste de
   White?  Entonces, ¿son válidos los resultados que se obtuvieron en
   el apartado [[item:a]]? ¿Y los del apartado [[item:b]]?
#+end_tcolorbox

#+latex: \gretl{hprice1-c1.txt}

#+latex: \gretl{hprice1-c2.txt}

#+begin_tcolorbox
#+ATTR_LATEX: :options [a), resume = questions]
d) Obtenga las estimaciones de mínimos cuadrados ponderados (MCP) bajo
   el supuesto de que la varianza condicional del término de error es
   proporcional a \lotsize:
   #+begin_export latex
   \begin{equation*}
     E(u^{2}_{i} | \bm{x}_{i}) = \sigma^{2}\lotsize_{i}.
   \end{equation*}
   #+end_export
   ¿Qué variables tienen efectos significativos? ¿Son similares las
   estimaciones a las obtenidas con MCO? Obtenga los resultados de la
   estimación MCP con errores típicos robustos a
   heteroscedasticidad. ¿Hay algún cambio en la significación de las
   variables? ¿Puede dar una explicación a esos cambios?
#+end_tcolorbox

#+latex: \gretl[lastline=13]{hprice1-d1.txt}

#+latex: \gretl[lastline=14]{hprice1-d2.txt}

#+begin_tcolorbox
#+ATTR_LATEX: :options [a), resume = questions]
e) (\emph{Individual}) Estime el modelo del apartado [[item:a]] usando
   mínimos cuadrados ponderados factibles de acuerdo con el supuesto:
   #+begin_export latex
   \begin{equation*}
     E(u^{2}_{i} | \bm{x}_{i}) = \sigma^{2}\exp\big(
     \delta_{0}
     + \delta_{1} \bedrooms_{i}
     + \delta_{2} \colonial_{i}
     + \delta_{3} \lotsize_{i}
     + \delta_{4} \size_{i}
     \big).
   \end{equation*}
   #+end_export
   Utilice el procedimiento descrito en la sección /La
   heteroscedasticidad debe ser estimada: MCG factibles/ en las
   páginas 282 y siguientes del manual de Wooldridge. Obtenga los
   resultados con errores típicos robustos a heteroscedasticidad. ¿Qué
   conclusiones se pueden extraer ahora?
#+end_tcolorbox

#+latex: \gretl{hprice1-e1.txt}

#+latex: \gretl[lastline=14]{hprice1-e2.txt}


# Local Variables:
# ispell-local-dictionary: "spanish"
# End:
