#+TITLE: Discriminación en la concesión de hipotecas
#+SETUPFILE: ../setup.org

# Define macros for the variable names
#+LATEX_HEADER: \newcommand*{\approve}{\Var{approve}}
#+LATEX_HEADER: \newcommand*{\black  }{\Var{black  }}
#+LATEX_HEADER: \newcommand*{\hispan }{\Var{hispan }}
#+LATEX_HEADER: \newcommand*{\obrat  }{\Var{obrat  }}
#+LATEX_HEADER: \newcommand*{\loanprc}{\Var{loanprc}}
#+LATEX_HEADER: \newcommand*{\unem   }{\Var{unem   }}
#+LATEX_HEADER: \newcommand*{\self   }{\Var{self   }}
#+LATEX_HEADER: \newcommand*{\male   }{\Var{male   }}
#+LATEX_HEADER: \newcommand*{\married}{\Var{married}}
#+LATEX_HEADER: \newcommand*{\dep    }{\Var{dep    }}
#+LATEX_HEADER: \newcommand*{\sch    }{\Var{sch    }}
#+LATEX_HEADER: \newcommand*{\chist  }{\Var{chist  }}
#+LATEX_HEADER: \newcommand*{\pubrec }{\Var{pubrec }}



* Objetivo

Se estima un modelo lineal de probabilidad para determinar si existió
discriminación racial a la hora de conceder hipotecas en Boston
en 1990.

* Datos

Los datos provienen del trabajo de W. C. Hunter y M. B. Walker (1996):
"@@latex:\foreignlanguage{english}{The Cultural Affinity Hypothesis
and Mortgage Lending Decisions}@@",
/@@latex:\foreignlanguage{english}{Journal of Real Estate Finance and
Economics}@@/, 13, 57-70.  El fichero ~loanapp.csv~ contiene las
siguientes variables:

- \approve: variable ficticia que toma el valor 1 para aquellos
  solicitantes a los que se les concede un préstamo hipotecario.

- \black, \hispan: variables ficticias con las que se codifica la
  etnia de los solicitantes. Cada individuo se clasifica en uno de
  tres grupos: negro ($\black = 1$), hispano ($\hispan = 1$)
  o blanco (categoría por defecto).

- \obrat: porcentaje de la renta mensual del solicitante que se
  destina a otras obligaciones financieras.

- \loanprc: importe del préstamo solicitado como fracción del precio
  de la casa.

- \unem: tasa de desempleo en el sector de actividad del solicitante.

- \self: ficticia que toma el valor 1 si el solicitante trabaja por
  cuenta propia.

- \male: ficticia que toma el valor 1 si el solicitante es hombre.

- \married: ficticia que toma el valor 1 si el solicitante está
  casado.

- \dep: número de personas dependientes del solicitante.

- \sch: ficticia que toma el valor 1 si el solicitante completó la
  educación secundaria.

- \chist: ficticia que toma el valor 1 si el solicitante nunca se ha
  retrasado más de 60 días en sus pagos.

- \pubrec: ficticia que toma el valor 1 si el solicitante se ha
  declarado en quiebra en el pasado.

* Instrucciones

Responda a las siguientes preguntas. Use un nivel de significación del
$5\%$ para los contrastes.

#+ATTR_LATEX: :options [a)]
a) Estime un modelo lineal de probabilidad donde la variable
   dependiente es \approve y las explicativas son \black e
   \hispan. Presente la tabla de la regresión con errores típicos
   robustos a heteroscedasticidad. Interprete las estimaciones de los
   parámetros. Las variable explicativas, ¿son significativas
   individualmente?

   #+begin_answer
   Modelo lineal de probabilidad:
   #+begin_export latex
   \[
     \approve_i = \beta_0 + \beta_1 \black_i + \beta_2 \hispan_i + u_i.
   \]
   #+end_export
   La tabla siguiente muestra las estimaciones MCO junto con errores
   típicos robustos a heteroscedasticidad:
   #+latex: \gretl[firstline=2, lastline=12]{loanapp-a.txt}

   El parámetro $\beta_0$ se interpreta como la probabilidad de que se
   le conceda una hipoteca a un blanco:
   #+begin_export latex
   \[
     \beta_0 = \Pr(\approve_i = 1 | \black_i = 0, \hispan_i = 0).
   \]
   #+end_export
   De acuerdo con las estimaciones presentadas antes, esta
   probabilidad sería $0.91$.

   Los parámetros $\beta_1$ y $\beta_2$ miden la diferencia entre las
   probabilidades de concesión de negros e hispanos (respectivamente) con
   respecto a la probabilidad de concesión a un individuo de la categoría
   de referencia (blancos):
   #+begin_export latex
   \begin{gather*}
     \beta_1 = \Pr(\approve_i = 1 | \black_i = 1, \hispan_i = 0) - \beta_0, \\
     \beta_2 = \Pr(\approve_i = 1 | \black_i = 0, \hispan_i = 1) - \beta_0.
   \end{gather*}
   #+end_export
   Las estimaciones de MCO indican que los individuos pertenecientes a
   las minorías raciales en Estados Unidos tenían una menor probabilidad
   de acceder una hipoteca que los blancos: 24 puntos porcentuales menos
   en el caso de negros y 16 puntos porcentuales menos en el caso de
   hispanos.

   Los estadísticos $t$ para contrastar la significación individual de
   los parámetros $\beta_0$, $\beta_1$ y $\beta_2$ son elevados en
   valor absoluto y sus valores $p$ son inferiores a $\alpha =
   5\%$. Por tanto, todos los parámetros son significativamente
   distintos de $0$ a un nivel de significación de $5\%$
   #+end_answer

b) Contraste si los parámetros de las variables \black e \hispan son
   iguales.

   #+begin_answer
   La hipótesis nula de que los parámetros de \black e \hispan son
   iguales puede escribirse como: $H_0: \beta_1 - \beta_2 = 0$:
   #+latex: \gretl[lastline=4]{loanapp-b.txt}
   El contraste de Wald robusto a heteroscedasticidad toma el valor
   $2.5$ y su valor $p$ es $0.11$. En consecuencia, no se rechaza la
   hipótesis nula al nivel de significación $\alpha = 5\%$.
   #+end_answer
   #+latex: \clearpage{}

c) Añada la variable explicativa \obrat. Interprete la estimación del
   parámetro de esta variable. ¿Tiene un efecto significativo?

   #+begin_answer
   #+latex: \gretl[firstline=2, lastline=13]{loanapp-c.txt}
   La estimación de la pendiente de \obrat muestra que por cada punto
   porcentual adicional de renta que el solicitante destine a otras
   obligaciones financieras, la probabilidad de obtener la hipoteca
   disminuye en $0.6$ puntos porcentuales.

   El contraste $t$ de significación individual de \obrat rechaza la
   hipótesis nula al $5\%$ de significación. Un aumento de otras
   cargas financieras reduce significativamente la probabilidad de
   concesión de las hipotecas.
   #+end_answer

d) Añada las restantes variables del archivo de datos: \loanprc,
   \unem, \male, \married, \dep, \self, \sch, \chist y
   \pubrec. Presente las estimaciones de MCO junto con los errores
   típicos robustos a heteroscedasticidad.  Contraste la significación
   conjunta de todas las variables explicativas salvo \black e
   \hispan.

   #+begin_answer
   Resultados de la estimación por MCO con errores típicos robustos a
   heteroscedasticidad:
   #+latex: \gretl[firstline=2, lastline=22]{loanapp-d1.txt}
   #+latex: \clearpage{}

   Resultados del contraste robusto sobre la significación conjunta de
   todas las explicativas, salvo \black e \hispan:
   #+latex: \gretl[firstline=2, lastline=4]{loanapp-d2.txt}
   El estadístico $F$ es $13.5$, lo que representa un valor muy
   elevado para ser compatible con la hipótesis nula. El valor $p$ es
   extremadamente pequeño e inferior a $\alpha = 5\%$ por lo que se
   rechaza la hipótesis nula.
   #+end_answer

e) Al añadir las variables explicativas adicionales, ¿qué ha ocurrido
   con las estimaciones de los parámetros de \black e \hispan? ¿Siguen
   siendo individualmente significativas?  Contraste si los parámetros
   de estas dos variables son iguales.

   #+begin_answer
   Las estimaciones de los parámetros de \black e \hispan son
   considerablemente menores en valor absoluto que las obtenidas en el
   apartado a), especialmente en el caso de la pendiente de \black que
   pasa de $-0.24$ a $-0.16$. Estos cambios pueden deberse a
   diferencias sistemáticas entre los miembros de los diferentes
   grupos raciales en los valores de las variables añadidas (historial
   crediticio, cargas financieras, precariedad del empleo, nivel
   educativo, etc.). A pesar de que tomen valores absolutos más
   pequeños, las pendientes de \black e \hispan tienen signo negativo
   y son significativamente distintas de $0$ a un nivel de
   significación de $5\%$.

   Contraste de igualdad de los parámetros de \black e \hispan:
   #+latex: \gretl[lastline=4]{loanapp-e.txt}
   No parece haber diferencias significativas entre los parámetros de
   \black e \hispan para $\alpha = 5\%$. El valor del contraste es
   $0.76$ y el valor $p = 0.38$ es superior al nivel de significación
   $\alpha = 5\%$. No hay diferencias significativas en las
   probabilidades de concesión de hipotecas a individuos de diferentes
   minorías raciales.
   #+end_answer

f) Los resultados obtenidos, ¿son evidencia de discriminación en
   contra de las minorías raciales?

   #+begin_answer
   Los resultados obtenidos en el apartado e) muestran que la
   probabilidad de acceder a una hipoteca es distinta para blancos y
   para no blancos. Esta diferencia no puede ser atribuida a las
   variables que se han usado como explicativas: situación financiera
   del solicitante, situación laboral, situación familiar, sexo, nivel
   educativo e historial crediticio. La persistencia de diferencias en
   la concesión de hipotecas después de haber controlado por factores
   económicos y personales constituiría evidencia de la existencia de
   discriminación en contra de las minorías raciales.
   #+end_answer

g) ¿Es posible estimar el modelo del apartado d) por Mínimos Cuadrados
   Ponderados Factibles?

   #+begin_answer
   La varianza condicional del término de error es:
   #+begin_export latex
   \[
     \operatorname{var}(u_i | \bm{x}_i) = p_i (1 - p_i),
   \]
   #+end_export
   donde $p_i$ es la probabilidad de ocurrencia:
   #+begin_export latex
   \[
     p_i = \Pr(\approve_i = 1 | \bm{x}_i) = \beta_0 + \beta_1 \black_i +
     \beta_2 \hispan_i + \beta_3 \obrat_i + \dots + \beta_{12} \pubrec_i.
   \]
   #+end_export
   Para aplicar MCPF se deberían utilizar las ponderaciones
   #+begin_export latex
   \[
     w_i = \frac{1}{\hat{p}_i (1 - \hat{p}_i)},
   \]
   #+end_export
   donde $\hat{p}_i$ son las predicciones de MCO que se obtienen a
   partir de las estimaciones los parámetros:
   #+begin_export latex
   \[
     \hat{p}_i = \hat{\beta}_0 + \hat{\beta}_1 \black_i +
     \hat{\beta}_2 \hispan_i + \hat{\beta}_3 \obrat_i + \dots +
     \hat{\beta}_{12} \pubrec_i.
   \]
   #+end_export
   Para que se pueda usar MCPF es necesario que $0 < \hat{p}_i <
   1$. Si esta condición no se cumple, las ponderaciones y las
   varianzas del término de error no serían estrictamente positivas.

   Guardamos en la variable ~phat~ las predicciones del modelo
   estimado en el apartado d) y calculamos sus estadísticos
   descriptivos:
   #+latex: \gretl[firstline=2, lastline=9]{loanapp-g.txt}
   Las probabilidades de ocurrencia predichas no cumplen la condición
   para usar MCPF: el valor máximo de $\hat{p}_i$ es $1.14$.
   #+end_answer


# Local Variables:
# ispell-local-dictionary: "spanish"
# End:

#  LocalWords:  Wald MCPF
