#+TITLE: La curva de Phillips en España (1965--2023) --- Soluciones
#+SETUPFILE: ../setup.org

# Define macros for the variable names
#+LATEX_HEADER: % \newcommand*{\weight}{\Var{weight}}
#+LATEX_HEADER: \newcommand*{\covid}{\Var{covid}}

#+latex: \setcounter{section}{3}

* Instrucciones

#+latex: \setcounter{subsection}{1}


** Contrastes de raíces unitarias

#+begin_tcolorbox
Contraste la existencia de una raíz unitaria en las variables =infl=,
=dinfl=, =paro= y =paroc=. En todos los casos:

#+ATTR_LATEX: :options [a)]
1. Determine mediante la inspección de un gráfico de series
   temporales si es necesario incluir una tendencia lineal en la
   regresión de Dickey-Fuller.

2. Seleccione con el AIC el número de retardos a incluir en la
   regresión de Dickey-Fuller usando como máximo 3 retardos.
#+end_tcolorbox

#+ATTR_LATEX: :options [c]{0.45\textwidth}
#+begin_minipage
#+latex: \vspace{0pt}
#+ATTR_LATEX: :scale 0.5
[[file:phillips-infl.pdf]]
#+end_minipage
#+ATTR_LATEX: :options [c]{0.55\textwidth}
#+begin_minipage
#+latex: \gretl{phillips-adf-infl.txt}
#+end_minipage

#+ATTR_LATEX: :options [c]{0.45\textwidth}
#+begin_minipage
#+latex: \vspace{0pt}
#+ATTR_LATEX: :scale 0.5
[[file:phillips-d_infl.pdf]]
#+end_minipage
#+ATTR_LATEX: :options [c]{0.55\textwidth}
#+begin_minipage
#+latex: \gretl{phillips-adf-d_infl.txt}
#+end_minipage

#+ATTR_LATEX: :options [c]{0.45\textwidth}
#+begin_minipage
#+latex: \vspace{0pt}
#+ATTR_LATEX: :scale 0.5
[[file:phillips-paro.pdf]]
#+end_minipage
#+ATTR_LATEX: :options [c]{0.55\textwidth}
#+begin_minipage
#+latex: \gretl{phillips-adf-paro.txt}
#+end_minipage

#+ATTR_LATEX: :options [c]{0.45\textwidth}
#+begin_minipage
#+latex: \vspace{0pt}
#+ATTR_LATEX: :scale 0.5
[[file:phillips-paroc.pdf]]
#+end_minipage
#+ATTR_LATEX: :options [c]{0.55\textwidth}
#+begin_minipage
#+latex: \gretl{phillips-adf-paroc.txt}
#+end_minipage

No se observan claras tendencias crecientes o decrecientes a lo largo
de todo el periodo en los gráficos de la inflación, =inf=, la
diferencia de la inflación, =d_inf=, la tasa de paro observada,
=paro=, y el paro cíclico, =paroc=, por lo que se incluye únicamente
un término constante en las regresiones de Dickey-Fuller.

Se establece un número máximo de 3 retardos a considerar en las
regresiones del contraste. De acuerdo con el AIC, no se incluye ningún
retardo en los casos de la inflación y su primera diferencia, mientras
que se selecciona 1 retardo en el caso de =paro= y 3 retardos en el
caso de =paroc=.

Los resultados de los contrastes no permiten rechazar, al 5% de
significación, la existencia de una raíz unitaria en las series =infl=
y =paro=. La hipótesis de una raíz unitaria se rechaza en los casos de
la primera diferencia de la inflación, =d_inf=, y del paro cíclico,
=paroc=.


** Curva de Phillips estática

#+begin_tcolorbox
- Estime una curva de Phillips estática presentada en la ecuación (1)
  utilizando las variables =infl= y =paro=. Incluya en la estimación
  la variable =covid=. Obtenga los resultados de la regresión robustos
  a heteroscedasticidad y autocorrelación.
#+end_tcolorbox

#+latex: \gretl{phillips-static.txt}

#+begin_tcolorbox
- Atendiendo a los resultados obtenidos con los contrastes de raíces
  unitarias, ¿se cumplen los supuestos que garantizan buenas
  propiedades asintóticas de MCO con series temporales? La estimación
  de la curva de Phillips estática, ¿puede ser una regresión espuria?
#+end_tcolorbox

Las variables =infl= y =paro= presentan raíces unitarias por lo que
se incumple el supuesto *ST.1'*, que requiere la estacionariedad y la
dependencia débil de las series incluidas en la regresión. En esas
condiciones, es muy probable que los resultados de la estimación sean
espurios y no reflejen una relación genuina entre las variables.

** Curva de Phillips con expectativas


#+begin_tcolorbox
- Estime la ecuación (3) para $L = 0, 1, 2, 3$. Además de los
  retardos de =paroc=, incluya la ficticia =covid= como
  explicativa. Asegúrese de que todas las regresiones se estiman para
  el mismo periodo muestral.

- Determine el número óptimo de retardos de acuerdo con el BIC
  (criterio de Schwarz).
#+end_tcolorbox

El valor del BIC se minimiza cuando solo se incluye 1 retardo en el
modelo.

#+latex: \gretl{phillips-lags.txt}

#+begin_tcolorbox
- Obtenga los errores típicos robustos a heteroscedasticidad y
  autocorrelación del modelo seleccionado con el BIC.
#+end_tcolorbox

#+latex: \gretl{phillips-dyn.txt}


** Estimación del multiplicador de largo plazo

#+begin_tcolorbox
- A partir del modelo seleccionado en la sección anterior, estime un
  modelo como en la ecuación (4) donde se obtienen directamente los
  multiplicadores acumulativos y el multiplicador de largo plazo (siga
  incluyendo =covid= en esta estimación). Utilice errores típicos
  robustos a heteroscedasticidad y autocorrelación.
#+end_tcolorbox

Para obtener directamente la estimación de los multiplicadores
acumulados, se sustituyen todos los retardos de =paroc= excepto el
último por retardos de su primera diferencia, =d_paroc=.

#+latex: \gretl{phillips-lr-mult.txt}

#+begin_tcolorbox
- Con los resultados de la regresión anterior, contraste al $5\%$ la
  hipótesis de que el multiplicador de largo plazo es 0. En caso de
  que no se rechace, estime el modelo de la ecuación (5) que impone la
  hipótesis $\delta_L = 0$.
#+end_tcolorbox

En la regresión mostrada en el punto anterior, se obtuvo una
estimación del multiplicador de largo plazo, $\hat{\delta}_1 = 0.09$,
y de su error típico, $\hat{\sigma}_{\hat{\delta}_1} = 0.13$. El
estadístico $t$ resultante es $0.66$, por lo que no se rechaza al 5%
la hipótesis de que el multiplicador de largo plazo es igual a 0
(valor $p = 0.51$).

La siguiente tabla muestra la estimación del modelo bajo la hipótesis
nula de ausencia de efectos de largo plazo del paro cíclico sobre la
inflación.

#+latex: \gretl{phillips-lr-mult-0.txt}


# Local Variables:
# ispell-local-dictionary: "spanish"
# End:

#  LocalWords:  Hodrick Prescott
