#+TITLE: Desempleo y crecimiento del PIB --- Soluciones
#+SETUPFILE: ../setup.org

# Define macros for the variable names
#+LATEX_HEADER: \newcommand*{\unemp}{\Var{unemp}}
#+LATEX_HEADER: \newcommand*{\gY}{\Var{gY}}
#+LATEX_HEADER: \newcommand*{\covid}{\Var{covid}}

#+latex: \setcounter{section}{1}

* Datos

#+latex: \setcounter{subsection}{1}


** Descripción de las variables

#+begin_tcolorbox
- En adelante, se usarán las series =d_unemp= y =gY=. ¿Qué
  interpretación económica tienen?
#+end_tcolorbox

#+begin_tcolorbox
- Represente gráficamente y observe la evolución temporal de las
  variables =d_unemp= y =gY=.  ¿Se observan tendencias o algún otro
  tipo de no estacionariedad?
#+end_tcolorbox

#+ATTR_LATEX: :options [c]{0.45\textwidth}
#+begin_minipage
#+latex: \vspace{0pt}
#+ATTR_LATEX: :scale 0.5
[[file:unemp-d_unemp.pdf]]
#+end_minipage
#+ATTR_LATEX: :options [c]{0.55\textwidth}
#+begin_minipage
Algunas palabras sabias.
#+end_minipage

#+ATTR_LATEX: :options [c]{0.45\textwidth}
#+begin_minipage
#+latex: \vspace{0pt}
#+ATTR_LATEX: :scale 0.5
[[file:unemp-gY.pdf]]
#+end_minipage
#+ATTR_LATEX: :options [c]{0.55\textwidth}
#+begin_minipage
Algunas palabras sabias.
#+end_minipage

#+ATTR_LATEX: :options [c]{0.45\textwidth}
#+begin_minipage
#+latex: \vspace{0pt}
#+ATTR_LATEX: :scale 0.5
[[file:unemp-gYalt.pdf]]
#+end_minipage
#+ATTR_LATEX: :options [c]{0.55\textwidth}
#+begin_minipage
Algunas palabras sabias.
#+end_minipage


* Modelo estático

#+begin_tcolorbox
- Estime por mínimos cuadrados ordinarios, MCO, los parámetros de:
  #+begin_export latex
  \begin{equation}\label{eq:1}
    \Delta \unemp_t = \alpha + \beta\, \gY_t + u_t,
  \end{equation}
  #+end_export
  donde $\unemp_t$ es la tasa de paro en el periodo $t$, $\gY_t$ es la tasa
  de crecimiento porcentual del PIB real y $u_t$ es el término de
  error.
#+end_tcolorbox

#+latex: \gretl{unemp-static.txt}

#+begin_tcolorbox
- Evalúe la bondad del ajuste y la significación de la variable
  explicativa. ¿Cuál es la interpretación económica de los parámetros
  $\alpha$ y $\beta$?
#+end_tcolorbox

#+begin_tcolorbox
- Obtenga un gráfico de series temporales de los residuos. Represente
  también el correlograma de los residuos. ¿Se comportan como un ruido
  blanco?
#+end_tcolorbox

#+ATTR_LATEX: :options [c]{0.45\textwidth}
#+begin_minipage
#+latex: \vspace{0pt}
#+ATTR_LATEX: :scale 0.5
[[file:unemp-uhat.pdf]]
#+end_minipage
#+ATTR_LATEX: :options [c]{0.55\textwidth}
#+begin_minipage
Algunas palabras sabias.
#+end_minipage

#+ATTR_LATEX: :options [c]{0.45\textwidth}
#+begin_minipage
#+latex: \vspace{0pt}
#+ATTR_LATEX: :scale 0.5
[[file:unemp-corrgm-1.pdf]]
#+end_minipage
#+ATTR_LATEX: :options [c]{0.55\textwidth}
#+begin_minipage
Algunas palabras sabias.
#+end_minipage


* Análisis de intervención


#+begin_tcolorbox
- Estime por MCO los parámetros de:
  #+begin_export latex
  \begin{equation}\label{eq:2}
    \Delta \unemp_t = \alpha + \beta\, \gY_t + \theta\, \covid_t + u_t,
  \end{equation}
  #+end_export
  Comente los resultados obtenidos y compárelos con los de la
  estimación de la ecuación \eqref{eq:1}.
#+end_tcolorbox

#+latex: \gretl{unemp-covid.txt}


* Modelo de retardos distribuidos

#+begin_tcolorbox
- Use el menú /Editar | Modificar el modelo.../ de la ventana de la
  estimación de la ecuación \eqref{eq:2} y añada 5 retardos de la
  variable =gY=. Así se obtienen las estimaciones del modelo de
  retardos distribuidos:
  #+begin_export latex
  \begin{equation}\label{eq:3}
    \Delta \unemp_t =
    \alpha +
    \beta_0\, \gY_t +
    \beta_1\, \gY_{t-1} +
    \dots +
    \beta_5\, \gY_{t-5} +
    \theta\, \covid_t + u_t,
  \end{equation}
  #+end_export
  ¿Qué significan los parámetros estimados? ¿Cómo responde la tasa de
  paro a cambios en el crecimiento del PIB?
#+end_tcolorbox

#+latex: \gretl{unemp-dl.txt}

#+begin_tcolorbox
- Para calcular el multiplicador de largo plazo, $\delta_L = \sum
  \beta_i$, introduzca en la consola de Gretl las instrucciones:
  #+latex: \vspace*{1ex}
  #+begin_src gretl :eval no
    mult = $coeff[2:7]
    mult_lp = sum(mult)
  #+end_src
  #+latex: \vspace*{1ex}
  ¿Qué significa el valor obtenido? /[Nota: Para que funcionen
  adecuadamente las instrucciones anteriores los parámetros de =gY= y
  sus retardos deben de ocupar las posiciones 2 a 7 en la tabla de la
  regresión.]/
#+end_tcolorbox

#+latex: \gretl{unemp-dyn-mult.txt}

#+latex: \gretl{unemp-lr-mult.txt}

#+begin_tcolorbox
- Los multiplicadores acumulados, $\delta_j = \sum_{i=0}^j\beta_i$, se
  obtienen introduciendo en la consola de Gretl las siguientes líneas:
  #+latex: \vspace*{1ex}
  #+begin_src gretl :eval no
        mult_ac = cum(mult)
        mult_ac
  #+end_src
  #+latex: \vspace*{1ex}
  ¿Que interpretación tienen estos multiplicadores?
#+end_tcolorbox

#+latex: \gretl{unemp-cum-mult.txt}


#+begin_tcolorbox
- En [cite:@leon-ledesmaEndogeneityNaturalRate2002] se define la /tasa
  de crecimiento natural/ como aquella que mantiene constante el
  desempleo. El modelo de la ecuación \eqref{eq:3} implica que en
  equilibrio a largo plazo:
  #+begin_export latex
  \[
    \Delta \unemp_t =
    \alpha +
    \delta_L\, \gY.
  \]
  #+end_export
  La tasa de crecimiento natural sería la que hace que $\Delta
  \unemp_t = 0$, por lo que:
  #+begin_export latex
  \[
     \gY_n = -\alpha / \delta_L.
  \]
  #+end_export
  Esta tasa se puede obtener en la consola de Gretl con:
  #+latex: \vspace*{1ex}
  #+begin_src gretl :eval no
        gYn = -$coeff[1] / mult_lp
  #+end_src
  #+latex: \vspace*{1ex}
  De acuerdo con la estimación de la ecuación \eqref{eq:3}, ¿cuál
  sería la tasa trimestral de crecimiento necesaria para que no
  aumente el desempleo?
#+end_tcolorbox

#+latex: \gretl{unemp-nat-rate.txt}


#+print_bibliography:


# Local Variables:
# ispell-local-dictionary: "spanish"
# End:

#  LocalWords:  Gretl
