#+TITLE: Brechas salariales
#+SETUPFILE: ../setup.org

# Define macros for the variable names
#+LATEX_HEADER: % \newcommand*{\weight}{\Var{weight}}
#+LATEX_HEADER: \newcommand*{\salario}{\Var{salario}}
#+LATEX_HEADER: \newcommand*{\mujer}{\Var{mujer}}
#+LATEX_HEADER: \newcommand*{\edad}{\Var{edad}}
#+LATEX_HEADER: \newcommand*{\inmigr}{\Var{inmigr}}
#+LATEX_HEADER: \newcommand*{\otroidioma}{\Var{otro\_idioma}}
#+LATEX_HEADER: \newcommand*{\educsec}{\Var{educ\_sec}}
#+LATEX_HEADER: \newcommand*{\educsup}{\Var{educ\_sup}}
#+LATEX_HEADER: \newcommand*{\exper}{\Var{exper}}
#+LATEX_HEADER: \newcommand*{\antig}{\Var{antig}}
#+LATEX_HEADER: \newcommand*{\pub}{\Var{pub}}
#+LATEX_HEADER: \newcommand*{\ong}{\Var{ong}}
#+LATEX_HEADER: \newcommand*{\contrtemp}{\Var{contr\_temp}}
#+LATEX_HEADER: \newcommand*{\controtro}{\Var{contr\_otro}}
#+LATEX_HEADER: \newcommand*{\parcial}{\Var{parcial}}
#+LATEX_HEADER: \newcommand*{\cualalta}{\Var{cual\_alta}}
#+LATEX_HEADER: \newcommand*{\cualmedia}{\Var{cual\_media}}
#+LATEX_HEADER: \newcommand*{\mujerexper}{\Var{mujer\_exper}}
#+LATEX_HEADER: \newcommand*{\mujersqexper}{\Var{mujer\_sq\_exper}}


* Objetivo

Se estimarán modelos de regresión para determinar la magnitud de la
*brecha salarial* que padecen las mujeres en España.

* Datos

Para estudiar la situación de la mujer en el mercado laboral español
se utilizarán los datos del Programa para la Evaluación Internacional
de las Competencias de los Adultos (PIAAC) de la OCDE.  El PIAAC es
una iniciativa de la OCDE para valorar el nivel de conocimientos y el
grado y distribución de destrezas de la población adulta a lo largo de
su vida laboral, entre los 16 y los 65 años. Esta evaluación se
encuadra en un marco comparativo coherente para poder establecer
contrastes internacionales.

** Variables originales

El archivo ~piaac-es.csv~ contiene una pequeña parte de los datos para
España del segundo ciclo del PIAAC, recopilados entre septiembre de
2022 y mayo de 2023. A continuación se muestran las variables
seleccionadas y su codificación:

#+latex: \begin{otherlanguage}{english}

- ~EARNHRBONUS~: Hourly earnings including bonuses for wage and salary
  earners.

- ~GENDER_R~: Person gender.

  #+latex: \vspace*{1.5ex}
  #+ATTR_LATEX: :booktabs t :align cp{9cm}
  | *Value* | *Description* |
  |---------+---------------|
  |       1 | Male          |
  |       2 | Female        |
  |---------+---------------|
  #+latex: \vspace*{1.5ex}

- ~AGE_R~: Person age in years.

- ~C_Q09~: Years of paid work during lifetime.

- ~D_Q03~: Current work: economic sector.

  #+latex: \vspace*{1.5ex}
  #+ATTR_LATEX: :booktabs t :align cp{9cm}
  | *Value* | *Description*                                                                                        |
  |---------+------------------------------------------------------------------------------------------------------|
  |       1 | The private sector (for example a company)                                                           |
  |       2 | The public sector (for example the local government or a state school)                               |
  |       3 | A non-profit organisation (for example a charity, professional association or religious organisation |
  |---------+------------------------------------------------------------------------------------------------------|
  #+latex: \vspace*{1.5ex}

- ~D_Q05a1~: Current work:  Current work - Start of work for employer - Age.

- ~D2_Q10_C~: Current work - Type of contract (3 categories).

  #+latex: \vspace*{1.5ex}
  #+ATTR_LATEX: :booktabs t :align cp{9cm}
  | *Value* | *Description*                                      |
  |---------+----------------------------------------------------|
  |       1 | An indefinite contract                             |
  |       2 | A fixed term contract, including seasonal contract |
  |       3 | Other                                              |
  |---------+----------------------------------------------------|
  #+latex: \vspace*{1.5ex}

- ~D_Q10~: Current work - Hours/week.

- ~ISCOSKIL4~: Occupational classification of respondent's job (4
  skill based categories), last or current.

  #+latex: \vspace*{1.5ex}
  #+ATTR_LATEX: :booktabs t :align cp{9cm}
  | *Value* | *Description*                         |
  |---------+---------------------------------------|
  |       1 | Skilled occupations                   |
  |       2 | Semi-skilled white-collar occupations |
  |       3 | Semi-skilled blue-collar occupations  |
  |       4 | Elementary occupations                |
  |---------+---------------------------------------|
  #+latex: \vspace*{1.5ex}

- ~EDCAT7~: Highest level of formal education obtained (7 categories).

  #+latex: \vspace*{1.5ex}
  #+ATTR_LATEX: :booktabs t :align cp{9cm}
  | *Value* | *Description*                                  |
  |---------+------------------------------------------------|
  |       1 | Primary or less (ISCED 1 or less)              |
  |       2 | Lower secondary (ISCED 2, ISCED 3C short)      |
  |       3 | Upper secondary (ISCED 3A-B, C long)           |
  |       4 | Post-secondary, non-tertiary (ISCED 4A-B-C)    |
  |       5 | Tertiary - professional degree (ISCED 5B)      |
  |       6 | Tertiary - bachelor degree (ISCED 5A)          |
  |       7 | Tertiary - master/research degree (ISCED 5A/6) |
  |---------+------------------------------------------------|
  #+latex: \vspace*{1.5ex}

- ~BORNLANG~: Interactions between place of birth and language status.

  #+latex: \vspace*{1.5ex}
  #+ATTR_LATEX: :booktabs t :align cp{9cm}
  | *Value* | *Description*                     |
  |---------+-----------------------------------|
  |       1 | Native-born and native-language   |
  |       2 | Native-born and foreign-language  |
  |       3 | Foreign-born and native-language  |
  |       4 | Foreign-born and foreign-language |
  |---------+-----------------------------------|
  #+latex: \vspace*{1.5ex}


#+latex: \end{otherlanguage}

** Transformación de las variables

Antes de estimar los modelos de regresión, es necesario transformar
las variables originales y crear algunas nuevas.

*** Salarios

- Cree la variable ~salario~ que toma los mismos valores que
  ~EARNHRBONUS~.

- Cree otra variable con el logaritmo del ~salario~.

*** Variables demográficas

Cree las siguientes variables:

- ~mujer~: variable ficticia que toma el valor 1 para las mujeres y 0
  para los hombres. Se construye a partir de la variable ~GENDER_R~.

- ~edad~: edad en años. Coincide con ~AGE_R~.

- ~inmigr~: ficticia que toma el valor 1 si el trabajador nació fuera
  de España. Se construye a partir de ~BORNLANG~.

- ~otro_idioma~: ficticia que toma el valor 1 si el idioma principal
  es extranjero. Se construye a partir de ~BORNLANG~.


*** Nivel educativo

El nivel educativo de los trabajadores se clasifica en tres grupos:
educación primaria o inferior (categoría de referencia), educación
secundaria y educación superior.  Defina las siguientes variables:

- ~educ_sec~: ficticia que toma el valor 1 si se completó algún nivel
  de educación secundaria. Se construye a partir de ~EDCAT7~ (/lower
  secondary/, /upper secondary/ y /post-secondary, non-tertiary/).

- ~educ_sup~: ficticia que toma el valor 1 si se completó algún
  nivel de educación superior. Se construye a partir de ~EDCAT7~
  (/tertiary/).


*** Situación laboral

Construya las siguientes variables:

- ~exper~: años de experiencia laboral. Coincide con ~C_Q09~.

- ~sq_exper~: cuadrado de ~exper~.

- ~antig~: años de antigüedad en la empresa. Se calcula a partir de
  ~edad~ y ~D_Q05a1~, variable que registra la edad a la que comenzó a
  trabajar para la empresa.


*** Tipo de empresa

Las empresas para las que trabajan los asalariados se clasifican en:
privadas (categoría de referencia), públicas o sin ánimo de lucro.
Cree las siguientes variables:

- ~pub~: ficticia que toma el valor 1 para los trabajadores del sector
  público. Se construye a partir de ~D_Q03~.

- ~ong~: ficticia que toma el valor 1 para los trabajadores de
  instituciones sin ánimo de lucro. Se construye a partir de ~D_Q03~.


*** Tipo de contrato laboral

Los contratos laborales de los asalariados se clasifican en:
indefinido (categoría de referencia), temporal y otros contratos
(aprendizaje, contrato verbal, sin contrato, etc.). Defina las
siguientes variables:

- ~contr_temp~: ficticia que toma el valor 1 si el contrato es
  temporal. Se construye a partir de ~D2_Q10_C~.

- ~contr_otro~: ficticia que toma el valor 1 si el contrato no es
  indefinido ni temporal. Se construye a partir de ~D2_Q10_C~.

También es útil distinguir entre trabajadores a jornada completa o a
tiempo parcial. Cree la siguiente variable:

- ~parcial~: ficticia que toma el valor 1 si la jornada no es completa
  (menos de 35 horas a la semana). Se calcula a partir de ~D_Q10~.

*** Cualificación del puesto de trabajo

Se clasifican en ocupaciones de cualificación baja (categoría
omitida), media y alta. Construya las siguientes variables:

- ~cual_alta~: ficticia que toma el valor 1 para puestos de trabajo de
  alta cualificación. Se construye a partir de ~ISCOSKIL4~ (/skilled
  occupations/).

- ~cual_media~: ficticia que toma el valor 1 para puestos de trabajo
  de cualificación media. Se construye a partir de ~ISCOSKIL4~
  (/semi-skilled occupations/).

* Instrucciones

En esta sección se plantea la estimación de *ecuaciones de salarios*:
modelos econométricos que explican los salarios (usualmente en
logaritmos) a partir de características de los trabajadores
(cualificación académica, experiencia laboral, etc.) y de su puesto de
trabajo (tipo de empresa, tipo de contrato, etc.).

** Preparación de los datos

A partir de los datos contenidos en ~piaac-es.csv~ cree las variables
descritas en la sección [[Transformación de las variables]].

- Incluya una tabla con los estadísticos descriptivos de las
  variables: ~salario~, ~edad~, ~inmigr~, ~otro_idioma~, ~educ_sec~,
  ~educ_sup~, ~exper~, ~antig~, ~pub~, ~ong~, ~contr_temp~,
  ~contr_otro~, ~parcial~, ~cual_alta~ y ~cual_media~.

  #+begin_answer
    #+latex: \gretl[lastline=18]{wagegap-a.txt}
  #+end_answer

** Brecha salarial no ajustada

La *brecha salarial no ajustada* mide la diferencia entre los salarios
que perciben las mujeres y los que perciben los hombres sin tener en
cuenta ninguna otra característica de los trabajadores. Se estima a
partir de un modelo de regresión simple cuya variable dependiente es
el logaritmo del salario y la variable explicativa es ~mujer~:
#+begin_export latex
\begin{equation}\label{eq-mod1}
  \log(\salario) =
  \beta_0
  + \beta_1 \mujer
  + u
\end{equation}
#+end_export

- ¿Cuál es la interpretación del parámetro $\beta_1$?

  #+begin_answer
    El parámetro $\beta_{1}$ mide cuál es la diferencia relativa entre
    el salario medio de las mujeres y el de los hombres. Por término
    medio, el salario de una mujer es aproximadamente un
    $100\beta_{1}\%$ mayor que el de un hombre. Cuando $\beta_1 < 0$,
    existe una brecha salarial desfavorable para las mujeres.
  #+end_answer

- Estime los parámetros del modelo de la ecuación \eqref{eq-mod1} y
  presente una tabla con los resultados. Utilice errores típicos
  robustos a heteroscedasticidad.

  #+begin_answer
    #+latex: \gretl[lastline=14]{wagegap-b.txt}
  #+end_answer

- Contraste la existencia de una brecha salarial desfavorable para las
  mujeres.

  #+begin_answer
    La hipótesis nula del contraste es $\beta_1 = 0$. No habría
    diferencia en los salarios de hombres y mujeres si $H_0$ es
    cierta. La hipótesis alternativa es que el salario de las mujeres
    es menor que el de los hombres lo que implica que $\beta_1 <
    0$. La $H_1$ es unilateral, por lo que la región de rechazo se
    concentra en la cola negativa.
    #+latex: \vspace*{1ex}

    Para encontrar el valor crítico, en primer lugar, se busca el valor
    que deja el \pct{5} de probabilidad en la cola derecha de una $t$ con
    \num{2909} grados de libertad (en Gretl se pueden consultar las tablas
    estadísticas en el menú /Herramientas/). En segundo lugar, dado que la
    región de rechazo se halla en la cola izquierda, se cambia el signo al
    valor encontrado en las tablas. Por tanto, el valor crítico es $c =
    \num{-1.65}$.
    #+latex: \vspace*{1ex}

    La regla de decisión consiste en comparar el cociente $t$ con el
    valor crítico y se rechazará la hipótesis nula si $t < c$. De
    acuerdo con los resultados de la regresión, se rechaza la
    hipótesis nula para $\alpha = 5\%$, puesto que $t = -6.29 < c =
    -1.65$.
    #+latex: \vspace*{1ex}

    En conclusión, los resultados de las estimaciones muestran que las
    mujeres tienen un salario medio aproximadamente un \pct{13}
    inferior al de los hombres y que esta diferencia es
    estadísticamente significativa.
  #+end_answer
  #+latex: \ClearPage

** Brecha salarial ajustada

La *brecha salarial ajustada* tiene en cuenta otras variables que
capturan características individuales y del puesto de trabajo. La
estimaremos a partir del modelo de regresión múltiple:
#+begin_export latex
\begin{equation}\label{eq-mod2}
  \begin{aligned}
  \log(\salario) =\, &\beta_0
    + \beta_{1}\, \mujer
    + \beta_{2}\, \edad
    + \beta_{3}\, \inmigr
    + \beta_{4}\, \otroidioma
    \, + \\ &\beta_{5}\, \educsec
    + \beta_{6}\, \educsup
    + \beta_{7}\, \exper
    + \beta_{8}\, \exper^2
    + \beta_{9}\, \antig
    \, + \\ &\beta_{10}\, \pub
    + \beta_{11}\, \ong
    + \beta_{12}\, \contrtemp
    + \beta_{13}\, \controtro
    + \beta_{14}\, \parcial
    \, + \\ &\beta_{15}\, \cualalta
    + \beta_{16}\, \cualmedia
    + u
\end{aligned}
\end{equation}
#+end_export

- Estime los parámetros de la ecuación \eqref{eq-mod2} y presente una
  tabla con los resultados. Utilice errores típicos robustos a
  heteroscedasticidad.

  #+begin_answer
    #+latex: \gretl[lastline=29]{wagegap-c.txt}
  #+end_answer
  #+latex: \ClearPage

- Contraste la presencia de heteroscedasticidad con el contraste de
  Breusch-Pagan (Koenker).

  #+begin_answer
    #+latex: \gretl[lastline=6]{wagegap-d.txt}

    El valor $p$ del contraste es inferior al nivel de significación
    (valor $p = 0.02 < \alpha = 0.05$), por lo que se rechaza la
    hipótesis de homoscedasticidad.
  #+end_answer

- Contraste la significación conjunta de los parámetros $\beta_{2},
  \beta_{3}, \dots, \beta_{16}$.

  #+begin_answer
    #+latex: \gretl{wagegap-e.txt}

    Los resultados del contraste rechazan, para un nivel de
    significación del \pct{5}, la hipótesis $\beta_{2} = \beta_3 =
    \dots = \beta_{16} = 0$. En conclusión, sin considerar la ficticia
    \mujer, las restantes variables explicativas aportan información
    relevante para explicar el salario.
  #+end_answer

- Interprete la estimación obtenida del parámetro $\beta_{3}$ y
  determine si es significativo.

  #+begin_answer
    El parámetro $\beta_{3}$ es la pendiente de la variable ficticia
    \inmigr. Su valor estimado es \num{-0.053}, lo que indicaría que
    el salario de los trabajadores nacidos en el extranjero es, en
    promedio, un \pct{5.3} menor que el de los nacidos en España,
    manteniendo constantes el resto de factores. El parámetro no es
    significativamente distinto de $0$, ya que su valor $p = 0.055$ es
    ligeramente superior al nivel de significación del \pct{5}.
  #+end_answer

- ¿Hay grandes diferencias entre las estimaciones de la brecha
  salarial ajustada y no ajustada?

  #+begin_answer
    Al introducir variables explicativas adicionales, la estimación de
    la brecha salarial aumenta hasta aproximadamente un \pct{16}.  La
    diferencia entre las dos estimaciones de la brecha es de una
    magnitud similar al error típico (aproximadamente $0.02$), por lo
    que, desde el punto de vista estadístico, ambas estimaciones no
    difieren significativamente.
  #+end_answer
  #+latex: \ClearPage



** Otros contrastes

Los modelos considerados hasta ahora no admiten la posibilidad de que
determinadas características de los trabajadores tengan una influencia
en el salario que sea diferente para hombres y para mujeres.

- Amplíe el modelo \eqref{eq-mod1} de forma que la experiencia laboral
  pueda tener efectos diferentes para hombres y para
  mujeres. Contraste la hipótesis de que no hay diferencias en la
  valoración de la experiencia laboral de hombres y mujeres.  ¿Qué
  conclusión se obtiene?

  #+begin_answer
    Se crean dos variables adicionales interactuando la variable
    \mujer con la experiencia laboral y su cuadrado:
    #+begin_export latex
    \begin{gather*}
      \mujerexper = \mujer \cdot \exper \\
      \mujersqexper = \mujer \cdot \exper^{2}
    \end{gather*}
    #+end_export
    Se incluyen estas interacciones en el modelo \eqref{eq-mod2}:
    #+begin_export latex
      \begin{equation}\label{eq-mod3}
        \begin{aligned}
        \log(\salario) =\, &\beta_0
          + \beta_{1}\, \mujer
          + \beta_{2}\, \edad
          + \beta_{3}\, \inmigr
          + \beta_{4}\, \otroidioma
          \, + \\ &\beta_{5}\, \educsec
          + \beta_{6}\, \educsup
          + \beta_{7}\, \exper
          + \beta_{8}\, \exper^2
          + \beta_{9}\, \antig
          \, + \\ &\beta_{10}\, \pub
          + \beta_{11}\, \ong
          + \beta_{12}\, \contrtemp
          + \beta_{13}\, \controtro
          \, + \\ &\beta_{14}\, \parcial
          + \beta_{15}\, \cualalta
          + \beta_{16}\, \cualmedia
          \, + \\ &\beta_{17}\, \mujerexper
          + \beta_{18}\, \mujersqexper
          + u
      \end{aligned}
      \end{equation}
    #+end_export
    Estimación por MCO con errores típicos robustos:
    #+latex: \gretl[lastline=31]{wagegap-f.txt}

    Si no hay diferencias en la valoración de la experiencia laboral
    de hombres y mujeres, se cumpliría la hipótesis nula: $\beta_{17}
    = \beta_{18} = 0$.
    #+latex: \gretl{wagegap-g.txt}
    El contraste de significación conjunta de las interacciones de
    \mujer con \exper y $\exper^2$ rechaza la hipótesis nula (valor $p
    = 0.035 < \alpha = 0.05$). Se concluye que existen diferencias
    significativas en cómo se retribuye la experiencia laboral a
    hombres y mujeres.
  #+end_answer

- Contraste la hipótesis de que la experiencia laboral sólo es
  determinante para los hombres y no afecta al salario de las mujeres.

  #+begin_answer
    A partir de la ecuación \eqref{eq-mod3}, se puede escribir la
    ecuación de salarios para las mujeres como:
     #+begin_export latex
      \begin{equation*}
        \begin{aligned}
        \log(\salario) =\, &(\beta_0 + \beta_{1})
          + \beta_{2}\, \edad
          + \beta_{3}\, \inmigr
          + \beta_{4}\, \otroidioma
          \, + \\ &\beta_{5}\, \educsec
          + \beta_{6}\, \educsup
          + (\beta_{7} + \beta_{17})\, \exper
          + (\beta_{8} + \beta_{18})\, \exper^2
          \, + \\ &\beta_{9}\, \antig
          + \beta_{10}\, \pub
          + \beta_{11}\, \ong
          + \beta_{12}\, \contrtemp
          + \beta_{13}\, \controtro
          \, + \\ &\beta_{14}\, \parcial
          + \beta_{15}\, \cualalta
          + \beta_{16}\, \cualmedia
          + u
      \end{aligned}
      \end{equation*}
    #+end_export
    Si la experiencia laboral no influyera en el salario de las mujeres se debería cumplir la hipótesis nula:
    #+begin_export latex
    \[
      H_{0}\!:
      \begin{cases}
        \beta_{7} + \beta_{17} = 0 \\
        \beta_{8} + \beta_{18} = 0
      \end{cases}
    \]
    #+end_export
    Contraste de Wald robusto a heteroscedasticidad:
    #+latex: \gretl{wagegap-h.txt}
    Por tanto se rechaza la hipótesis nula a un nivel de significación
    del \pct{5}. La experiencia laboral sí afecta al salario de las
    mujeres.
  #+end_answer

* COMMENT Participación en el mercado laboral (Opcional e individual)

En esta sección se estudiará la incorporación de la mujer al mercado
de trabajo utilizando modelos lineales de probabilidad donde la
variable dependiente es la variable ficticia ~activ~ que toma el
valor 1 para las personas que participan en el mercado de trabajo.


** Modelo de probabilidad lineal simple

Se pueden medir las diferencias en las tasas de actividad de mujeres y
hombres estimando el modelo de regresión simple:
#+begin_export latex
\begin{equation}\label{eq-mod3}
  \activ = \alpha_0
    + \alpha_1 \mujer
    + v
\end{equation}
#+end_export

- Estime los parámetros del modelo de la ecuación \eqref{eq-mod3} y
  presente una tabla con los resultados.

  #+begin_answer

  #+end_answer

- Calcule, a partir de las estimaciones de los parámetros, las tasas
  de actividad de hombres y mujeres.

  #+begin_answer

  #+end_answer

- Usando los resultados de la regresión, ¿qué diferencia hay entre las
  tasas de actividad de hombres y mujeres?  ¿Es significativa esa
  diferencia?

  #+begin_answer

  #+end_answer


** Modelo de probabilidad lineal múltiple

Se añaden más variables explicativas a la ecuación \eqref{eq-mod3}:
#+begin_export latex
\begin{equation}\label{eq-mod4}
\begin{aligned}
  \activ =\, &\alpha_0
    + \alpha_1 \mujer
    + \alpha_2 \educ
    + \alpha_3 \exper
    \,+\\ & \alpha_4 edad
    + \alpha_5 \hijos
    + \alpha_6 \inmigr
    + \alpha_7 \pareja
    + v
\end{aligned}
\end{equation}
#+end_export


- Estime los parámetros del modelo de la ecuación \eqref{eq-mod4} y
  presente una tabla con los resultados.

- Contraste la significación conjunta de las variables añadidas en la
  ecuación \eqref{eq-mod4}.

- Interprete la estimación obtenida del parámetro $\alpha_{5}$ y
  determine si es significativo.

- ¿Son muy diferentes las estimaciones del parámetro $\alpha_1$ de la
  ecuación \eqref{eq-mod3} y la ecuación \eqref{eq-mod4}? En caso de
  que su respuesta sea afirmativa, ¿a qué se debe esa diferencia?

- ¿Es posible estimar el modelo de la ecuación \eqref{eq-mod4} por
  mínimos cuadrados ponderados factibles (MCPF)? Si su respuesta es
  afirmativa obtenga las estimaciones MCPF y, si es negativa, explique
  por qué no pueden obtenerse.


# Local Variables:
# ispell-local-dictionary: "spanish"
# End:

#  LocalWords:  PIAAC OCDE Breusch Koenker
