#+TITLE: La mujer en el mercado laboral español --- Soluciones
#+SETUPFILE: ../setup.org

# Define macros for the variable names
#+LATEX_HEADER: % \newcommand*{\weight}{\Var{weight}}
#+LATEX_HEADER: \newcommand*{\lsalario}{\Var{lsalario}}
#+LATEX_HEADER: \newcommand*{\activ   }{\Var{activ   }}
#+LATEX_HEADER: \newcommand*{\mujer   }{\Var{mujer   }}
#+LATEX_HEADER: \newcommand*{\educ    }{\Var{educ    }}
#+LATEX_HEADER: \newcommand*{\exper   }{\Var{exper   }}
#+LATEX_HEADER: \newcommand*{\antig   }{\Var{antig   }}
#+LATEX_HEADER: \newcommand*{\pub     }{\Var{pub     }}
#+LATEX_HEADER: \newcommand*{\ong     }{\Var{ong     }}
#+LATEX_HEADER: \newcommand*{\temp    }{\Var{temp    }}
#+LATEX_HEADER: \newcommand*{\apr     }{\Var{apr     }}
#+LATEX_HEADER: \newcommand*{\otro    }{\Var{otro    }}
#+LATEX_HEADER: \newcommand*{\edad    }{\Var{edad    }}
#+LATEX_HEADER: \newcommand*{\hijos   }{\Var{hijos   }}
#+LATEX_HEADER: \newcommand*{\inmigr  }{\Var{inmigr  }}
#+LATEX_HEADER: \newcommand*{\pareja  }{\Var{pareja  }}

#+latex: \setcounter{section}{2}

* Ecuaciones de salarios

** Brecha salarial no ajustada

#+begin_tcolorbox
Considere el  modelo de regresión simple:
#+begin_export latex
\begin{equation}\label{eq-mod1}
  \lsalario =
  \beta_0
  + \beta_1 \mujer
  + u.
\end{equation}
#+end_export

- ¿Cuál es la interpretación del parámetro $\beta_1$?
#+end_tcolorbox

El parámetro $\beta_{1}$ mide cuál es la diferencia relativa entre el
salario medio de las mujeres y el de los hombres. Por término medio,
el salario de una mujer es aproximadamente un
@@latex:$100\beta_{1}\%$@@ mayor que el de un hombre. Cuando $\beta_1
< 0$, existe una brecha salarial desfavorable para las mujeres.

#+begin_tcolorbox
- Estime los parámetros del modelo de la ecuación \eqref{eq-mod1} y
  presente una tabla con los resultados.
#+end_tcolorbox

#+latex: \gretl{wagegap-a.txt}

#+begin_tcolorbox
- Contraste la existencia de una brecha salarial desfavorable para las
  mujeres.
#+end_tcolorbox

La hipótesis nula del contraste es $\beta_1 = 0$. No habría diferencia
en los salarios de hombres y mujeres si $H_0$ es cierta. La hipótesis
alternativa es que el salario de las mujeres es menor que el de los
hombres lo que implica que $\beta_1 < 0$. La $H_1$ es unilateral, por
lo que la región de rechazo se concentra en la cola negativa.

Para encontrar el valor crítico, en primer lugar, se busca el valor
que deja el \pct{5} de probabilidad en la cola derecha de una $t$ con
\num{2334} grados de libertad (en Gretl se pueden consultar las tablas
estadísticas en el menú /Herramientas/). En segundo lugar, dado que la
región de rechazo se halla en la cola izquierda, se cambia el signo al
valor encontrado en las tablas. Por tanto, el valor crítico es $c =
\num{-1.65}$.

La regla de decisión consiste en comparar el cociente $t$ del
parámetro $\beta_1$ con el valor crítico. Dado que éste se halla en la
cola negativa, se rechazará la hipótesis nula si $t < c$. De acuerdo
con los resultados de la regresión, el cociente $t = -6.14 < c =
-1.65$, por lo que se rechaza la hipótesis nula para @@latex:$\alpha =
5\%$@@.

En conclusión, los resultados de las estimaciones muestran que las
mujeres tienen un salario medio aproximadamente un \pct{13} inferior
al de los hombres y que esta diferencia es estadísticamente
significativa.


** Brecha salarial ajustada

#+begin_tcolorbox
Considere el modelo de regresión múltiple:
#+begin_export latex
\begin{equation}\label{eq-mod2}
  \begin{aligned}
  \lsalario =\, &\beta_0
    + \beta_1 \mujer
    + \beta_2 \educ
    + \beta_3 \exper
    + \beta_4 \antig
    \, + \\ &\beta_5 \pub
    + \beta_6 \ong
    + \beta_7 \temp
    + \beta_8 \apr
    + \beta_9 \otro
    \, + \\ &\beta_{10} \edad
    + \beta_{11} \hijos
    + \beta_{12} \inmigr
    + \beta_{13} \pareja
    + u
\end{aligned}
\end{equation}
#+end_export

- Estime los parámetros del modelo de la ecuación \eqref{eq-mod2} y
  presente una tabla con los resultados.
#+end_tcolorbox

#+latex: \gretl{wagegap-b.txt}

#+begin_tcolorbox
- Contraste la significación conjunta de los parámetros $\beta_{2},
  \beta_{3}, \dots, \beta_{13}$.
#+end_tcolorbox

#+latex: \gretl{wagegap-c.txt}

Los resultados del contraste rechazan, para un nivel de significación
del \pct{5}, la hipótesis $\beta_{2} = \beta_3 = \dots = \beta_{13} =
0$. En conclusión, sin considerar la ficticia \mujer, las restantes
variables explicativas aportan información relevante para explicar el
salario.


#+begin_tcolorbox
- Interprete la estimación obtenida del parámetro $\beta_{12}$ y
  determine si es significativo.
#+end_tcolorbox

El coeficiente $\beta_{12}$ es el parámetro de la ficticia \inmigr, su
valor es \num{-0.120} y es claramente significativo (valor $p$
inferior a \num{0.05}). Esto indica que el salario de los inmigrantes
es, en promedio, un \pct{12} menor que el de los nativos, manteniendo
constantes el resto de factores.

#+begin_tcolorbox
- ¿Hay diferencias entre las estimaciones de la brecha salarial no
  ajustada y de la ajustada?
#+end_tcolorbox

Al introducir variables explicativas adicionales en el modelo la
estimación de la brecha salarial de género no solo se mantiene, sino
que se amplía hasta aproximadamente un \pct{16}.

La *brecha no ajustada* compara los salarios medios entre hombres y
mujeres sin tener en cuenta otras características. Por tanto, no
considera que puedan existir diferencias sistemáticas entre ambos
grupos (por ejemplo, en nivel educativo, antigüedad o tipo de
contrato) que puedan explicar parte de la diferencia salarial
observada.

En cambio, al incorporar esas variables en el análisis, la *brecha
ajustada* permite comparar los salarios de hombres y mujeres con un
perfil similar (misma experiencia, misma cualificación, mismo tipo de
contrato, etc.). El hecho de que esta brecha ajustada sea mayor que la
no ajustada sugiere que, a igualdad de características, las mujeres
son penalizadas en mayor medida. Es decir, no solo cobran menos, sino
que sus cualificaciones parecen estar peor valoradas que las de los
hombres.

* Participación en el mercado laboral (Opcional e individual)


** Modelo de probabilidad lineal simple

#+begin_tcolorbox
Modelo de regresión simple:
#+begin_export latex
\begin{equation}\label{eq-mod3}
  \activ = \alpha_0
    + \alpha_1 \mujer
    + v
\end{equation}
#+end_export

- Estime los parámetros del modelo de la ecuación \eqref{eq-mod3} y
  presente una tabla con los resultados.
#+end_tcolorbox

#+latex: \gretl{wagegap-d.txt}

#+begin_tcolorbox
- Calcule, a partir de las estimaciones de los parámetros, las tasas
  de actividad de hombres y mujeres.
#+end_tcolorbox

Con las estimaciones anteriores podemos calcular la probabilidad de
que los hombres y mujeres de la muestra participen en la población
activa:
#+begin_export latex
\begin{align*}
  &\text{Hombres:\ } \hat{\alpha}_{0} = 0.83; \\
  &\text{Mujeres:\ } \hat{\alpha}_{0} + \hat{\alpha}_{1} = 0.72.
\end{align*}
#+end_export

#+begin_tcolorbox
- Usando los resultados de la regresión, ¿qué diferencia hay entre las
  tasas de actividad de hombres y mujeres?  ¿Es significativa esa
  diferencia?
#+end_tcolorbox

El parámetro $\alpha_1$ mide la diferencia en las tasas de actividad
de hombres y mujeres. La tasa de actividad de las mujeres es
\num{11.2} puntos porcentuales menor que la de los hombres y esta
diferencia es estadísticamente significativa (valor $p$ prácticamente
igual a 0).

** Modelo de probabilidad lineal múltiple

#+begin_tcolorbox
Modelo de regresión múltiple:
#+begin_export latex
\begin{equation}\label{eq-mod4}
\begin{aligned}
  \activ =\, &\alpha_0
    + \alpha_1 \mujer
    + \alpha_2 \educ
    + \alpha_3 \exper
    \,+\\ & \alpha_4 edad
    + \alpha_5 \hijos
    + \alpha_6 \inmigr
    + \alpha_7 \pareja
    + v
\end{aligned}
\end{equation}
#+end_export

- Estime los parámetros del modelo de la ecuación \eqref{eq-mod4} y
  presente una tabla con los resultados.
#+end_tcolorbox

#+latex: \gretl{wagegap-e.txt}

#+begin_tcolorbox
- Contraste la significación conjunta de las variables añadidas en la
  ecuación \eqref{eq-mod4}.
#+end_tcolorbox

#+latex: \gretl{wagegap-f.txt}

El valor del estadístico $F$ es muy grande y proporciona fuerte
evidencia de que las variables añadidas mejoran la capacidad
explicativa del modelo (valor $p$ prácticamente igual a \num{0}).

#+begin_tcolorbox
- Interprete la estimación obtenida del parámetro $\alpha_{5}$ y
  determine si es significativo.
#+end_tcolorbox

El parámetro $\alpha_5$ mide la diferencia en la probabilidad de
participar en la población activa dependiendo de si se tienen hijos
o no.  El coeficiente estimado muestra que la probabilidad de
pertenecer a la población activa es \num{7.7} puntos porcentuales
mayor en el caso de las personas con hijos, /ceteris paribus/. El
efecto de la variable \hijos es significativo (valor $p$ prácticamente
\num{0}).

#+begin_tcolorbox
- ¿Son muy diferentes las estimaciones del parámetro $\alpha_1$ de la
  ecuación \eqref{eq-mod3} y la ecuación \eqref{eq-mod4}? En caso de
  que su respuesta sea afirmativa, ¿a qué se debe esa diferencia?
#+end_tcolorbox

Al añadir otras variables al modelo, la estimación de $\alpha_1$ se
reduce a \num{6.6} puntos porcentuales, aunque sigue siendo
estadísticamente significativa. Esto sugiere que habría factores
observables (como, entre otros, la edad, el número de hijos o la
experiencia laboral) que explicarían parte de la menor participación
de las mujeres en el mercado laboral. Sin embargo, incluso después de
tener en cuenta estas características, una parte sustancial de la
diferencia en las tasas de actividad sigue asociada al hecho de ser
mujer, lo que sugiere la presencia de factores adicionales,
posiblemente de carácter estructural o social.


#+begin_tcolorbox
- ¿Es posible estimar el modelo de la ecuación \eqref{eq-mod4} por
  mínimos cuadrados ponderados factibles (MCPF)? Si su respuesta es
  afirmativa obtenga las estimaciones MCPF y, si es negativa, explique
  por qué no pueden obtenerse.
#+end_tcolorbox


En los modelos de probabilidad lineal se conoce cuál es la relación
entre la varianza del término de error y las explicativas:
#+begin_export latex
\[
\operatorname{var}(u_i|\bm{x}_i) = p(\bm{x}_i) \big(1 - p(\bm{x}_i)\big),
\]
#+end_export
donde
#+begin_export latex
\[
 p(\bm{x}_i) = \alpha_0 + \alpha_1 x_{1i} + \dots + \alpha_k x_{ki}.
\]
#+end_export
Es decir, $p_i = p(\bm{x}_i)$ sería la probabilidad de que $y_i = 1$
en función de los valores que toman las explicativas.

No es posible utilizar MCP en este caso ya que las probabilidades
dependen de los parámetros desconocidos $\alpha_0, \dots,
\alpha_k$. En principio se podría usar MCPF, utilizando como
ponderaciones la inversa de $\hat{h}_i = \hat{p}_i (1 - \hat{p}_i)$,
donde
#+begin_export latex
\[
 \hat{p}_i = \hat{\alpha}_0 + \hat{\alpha}_1 x_{1i} + \dots + \hat{\alpha}_k x_{ki}.
\]
#+end_export
Es decir, $\hat{p}_i$ son los valores ajustados obtenidos a partir de
la estimación MCO. Para que pueda aplicarse MCPF, $\hat{h}_i$ debe ser
mayor que \num{0}. Esto, a su vez, requiere que $0 < \hat{p}_i < 1$.

Después de obtener las estimaciones MCO de la ecuación \eqref{eq-mod4},
se calcularon los valores ajustados.

#+latex: \gretl{wagegap-g.txt}

Los estadísticos descriptivos de la tabla anterior muestran que el
valor mínimo de los valores ajustados es \num{0.065} y el valor máximo
es \num{1.45}. Por tanto, no es posible aplicar MCPF, dado que en este
caso no se cumple la condición que garantiza que la estimación de la
varianza del término de error es siempre positiva.

# Local Variables:
# ispell-local-dictionary: "spanish"
# End:
